# import sys, os
# import cv2
# import numpy as np
# import json
# import argparse
# import time
# import pandas


# import random

# # import SLAM components
# sys.path.insert(0, "{}/slam".format(os.getcwd()))
# from ekfNoLM import EKF
# from slam.robot import Robot
# import slam.aruco_detector as aruco


# # import utility functions
# sys.path.insert(0, "util")
# from util.pibot import PenguinPi
# import util.measure as measure


# from YOLO.detector import Detector
# import pathPlannerV2
# from Obstacle import *
# from math_functions import *
# from path_find_with_weight import *
# from localPathPlanner import *
# from Obstacle import *
    
# def get_angle_robot_to_goal(robot_state, goal):
#     if goal.shape[0] < 3:
#         goal = np.hstack((goal, np.array([0])))

#     x_goal, y_goal,_ = goal

#     x, y, theta = robot_state
#     x_diff = x_goal - x
#     y_diff = y_goal - y

#     alpha = clamp_angle(np.arctan2(y_diff, x_diff) - theta)
#     return alpha

# def clamp_angle(rad_angle=0, min_value=-np.pi, max_value=np.pi):
# 	"""
# 	Restrict angle to the range [min, max]
# 	:param rad_angle: angle in radians
# 	:param min_value: min angle value
# 	:param max_value: max angle value
# 	"""

# 	if min_value > 0:
# 		min_value *= -1

# 	angle = (rad_angle + max_value) % (2 * np.pi) + min_value

# 	return angle

# def get_distance_robot_to_goal(robot_state=np.zeros(3), goal=np.zeros(3)):
# 	"""
# 	Compute Euclidean distance between the robot and the goal location
# 	:param robot_state: 3D vector (x, y, theta) representing the current state of the robot
# 	:param goal: 3D Cartesian coordinates of goal location
# 	"""

# 	if goal.shape[0] < 3:
# 		goal = np.hstack((goal, np.array([0])))

# 	x_goal, y_goal,_ = goal
# 	x, y,_ = robot_state
# 	x_diff = x_goal - x
# 	y_diff = y_goal - y

# 	rho = np.hypot(x_diff, y_diff)

# 	return rho

# def generate_line_points(x, y, xEnd, yEnd, n_points=10):
#     # Calculate the step size for x and y directions
#     x_step = (xEnd - x) / (n_points - 1)
#     y_step = (yEnd - y) / (n_points - 1)

#     # Generate the points
#     points = []
#     for i in range(n_points):
#         new_x = x + i * x_step
#         new_y = y + i * y_step
#         points.append((new_x, new_y))
    
#     return points
     
# def update_robot_state(controlTime, lv, rv, landmarkPosition):
#     drive_meas = control(controlTime,lv,rv)
#     update_slam(drive_meas,landmarkPosition)
    
# def update_slam(drive_meas, lms):
    
#     ekf.predict(drive_meas)
#     ekf.add_landmarks(lms)
#     ekf.update(lms)
    
# def control(control_clock,lv,rv):
#     # lv,rv = ppi.set_velocity(driveCommand, wheel_vel)
#     dt = time.time() - control_clock
#     drive_meas = measure.Drive(lv,-rv,dt)
#     control_clock = time.time()
    
#     return drive_meas
    
# def estimate_pose(camera_matrix, obj_info, robot_pose):
#     """
#     function:
#         estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
#     input:
#         camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
#             |f_x, s,   c_x|
#             |0,   f_y, c_y|
#             |0,   0,   1  |
#             (f_x, f_y): focal length in pixels
#             (c_x, c_y): optical centre in pixels
#             s: skew coefficient (should be 0 for PenguinPi)
#         obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
#         robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
#     output:
#         target_pose: dict, prediction of target pose
#     """
#     # read in camera matrix (from camera calibration results)
#     focal_length = camera_matrix[0][0]

#     # there are 8 possible types of fruits and vegs
#     ######### Replace with your codes #########
#     # TODO: measure actual sizes of targets [width, depth, height] and update the dictionary of true target dimensions
#     target_dimensions_dict = {'pear': [156,151,0.0914], 'lemon': [1.0,1.0,0.0527], 
#                               'lime': [1.0,1.0,0.053], 'tomato': [1.0,1.0,0.058], 
#                               'capsicum': [1.0,1.0,0.0963], 'potato': [1.0,1.0,0.0563], 
#                               'pumpkin': [1.0,1.0,0.074], 'garlic': [1.0,1.0,0.0713],'orange': [1, 1, 79]}
#     #########

#     # estimate target pose using bounding box and robot pose
#     target_class = obj_info[0]     # get predicted target label of the box
#     target_box = obj_info[1]       # get bounding box measures: [x,y,width,height]
#     true_height = target_dimensions_dict[target_class][2]   # look up true height of by class label

#     # compute pose of the target based on bounding box info, true object height, and robot's pose
#     pixel_height = target_box[3]
#     pixel_center = target_box[0]
#     distance = true_height/pixel_height * focal_length  # estimated distance between the robot and the centre of the image plane based on height
#     # training image size 320x240p
#     image_width = 320 # change this if your training image is in a different size (check details of pred_0.png taken by your robot)
#     x_shift = image_width/2 - pixel_center              # x distance between bounding box centre and centreline in camera view
#     theta = np.arctan(x_shift/focal_length)     # angle of object relative to the robot
#     ang = theta + robot_pose[2]     # angle of object in the world frame
    
#    # relative object location
#     distance_obj = distance/np.cos(theta) # relative distance between robot and object
#     x_relative = distance_obj * np.cos(theta) # relative x pose
#     y_relative = distance_obj * np.sin(theta) # relative y pose
#     relative_pose = {'x': x_relative, 'y': y_relative}
#     #print(f'relative_pose: {relative_pose}')

#     # location of object in the world frame using rotation matrix
#     delta_x_world = x_relative * np.cos(robot_pose[2]) - y_relative * np.sin(robot_pose[2])
#     delta_y_world = x_relative * np.sin(robot_pose[2]) + y_relative * np.cos(robot_pose[2])
#     # add robot pose with delta target pose
#     target_pose = {'y': (robot_pose[1]+delta_y_world)[0],
#                    'x': (robot_pose[0]+delta_x_world)[0]}
#     #print(f'delta_x_world: {delta_x_world}, delta_y_world: {delta_y_world}')
#     #print(f'target_pose: {target_pose}')

#     return target_pose


# def plotCurrentPath(obstacles_default,G,pos,path,start_point,goal_point):
#     formatPathPlot = []
#     obstaclesList = []
#     radius = 0.12
#     for key,value in obstacles_default.items():
#         xCoord = value.get('x')
#         yCoord = value.get('y')
#         obstaclesList.append(Circle(xCoord, yCoord, radius=radius, name=key))        

#     for i in path:
#         formatPathPlot.append((i[0],i[1]))
        
#     plot_single_path_and_obstacles(G,pos,formatPathPlot,obstaclesList,start_point,goal_point)
    

# def lookForLM(image, nextWayPoint = None):
#     """Function that look for landmark in view of the robot
#             if nextWayPoint is None, 
#                 we are turning, don't need to check collusio

#     Args:
#         nextWayPoint (_type_, optional): _description_. Defaults to None.
#         if it is None:
#             we are turning, so no collision checking needed
#         else:
#             we are going straight, need to check if we are going to hit anything
        
#         outputs:
#             landmark : List of landmarks for updating position
#             isInCollision (bool): true if we are in collision
#             collisionPos: List of [x,y] of things that we are going to hit
#     """
#     COLLISION_DIS = 0.7
#     OBS_RADIUS = 0.1
    
#     isInCollision = False
#     collisionList = [] #list of coordiant that the robot will go into
#     landMarkCoord = []
#     landmarkPosition,_ = aruco_det.detect_marker_positions(image)
    
#     if nextWayPoint != None:
#         disToWaypoint = math.sqrt((nextWayPoint[0]-robot.state[0][0])**2 + (nextWayPoint[1]-robot.state[1][0])**2)
        
#         if disToWaypoint > COLLISION_DIS: #we won't look beyond 0.2m for collision
#             points = generate_line_points(robot.state[0],robot.state[1], (nextWayPoint[0]+robot.state[0])/2,(nextWayPoint[1]+robot.state[1])/2)
#         else:
#             points = generate_line_points(robot.state[0],robot.state[1], nextWayPoint[0],nextWayPoint[1])
        
#         for landmark in landmarkPosition:
#             gobalLM = ekf.compute_gobal_marker(landmark)
#             obsCircle = Circle(gobalLM[0][0],gobalLM[1][0],OBS_RADIUS,landmark.tag)
#             inCollision, collisionPoint = obsCircle.is_in_collision_with_points(points)
#             landMarkCoord.append([gobalLM[0][0],gobalLM[1][0]])
#             if inCollision:
#                 collisionList.append([gobalLM[0][0] , gobalLM[1][0]])
#                 isInCollision = True
#     else:
#         return landmarkPosition, collisionList, isInCollision,landMarkCoord
    
#     return landmarkPosition, collisionList, isInCollision,landMarkCoord
        
  
# def lookForFruit(targetName, image, nextWayPoint = None):
#     """Function that look for fruit in the view of the robot
#         if it sees an fruit in the way of the robot
#             return list of collision points
        
#         if there's no fruit in the view of the robot
#             if it sees the target in view 
#                 check if the target is around where we expect it to be
#                     if it is within a radius from true map, it is the target
                    
#         if nextWayPoint is None, we are turning
#             if we see the target, 
            
#     Args:
#         image (_type_): _description_
#         nextWayPoint (_type_, optional): _description_. Defaults to None.
#     """
    
#     # targetName = search_list[0].split('_')[0]
#     targetInView = False
#     isInCollision = False
#     inCollision = False
#     collisionList = []
#     targetCoord = []
#     allFruitInView = [] #coord of all the fruit in view
                
#     yolo_input_img = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
#     detector_output, yolo_vis = yolo.detect_single_image(yolo_input_img)
    

#     for object in detector_output:
#         print(f"========seeing {object[0]} target is {targetName}")
#         targetPose  = estimate_pose(camera_matrix, object, ekf.robot.state)
#         targetX = targetPose.get('x')
#         targetY = targetPose.get('y')
#         allFruitInView.append([targetX,targetY])
        
#         if object[0] == targetName:
#             #checking if it is the real target
#             targetInView = True
#             targetCoord = [targetX,targetY]
#         else: # if we are seeing the target, don't need to check collusion
#             if nextWayPoint != None:
#                 #since we are going straight, we need to check what's in front of us
                
#                 disToWaypoint = math.sqrt((nextWayPoint[0]-robot.state[0])**2 + (nextWayPoint[1]-robot.state[1])**2)
#                 #if the next way point is too far away, we don't need to check collusion
#                 points = generate_line_points(robot.state[0][0],robot.state[1][0], nextWayPoint[0],nextWayPoint[1])
#                 # if disToWaypoint > 0.2:
#                 #     points = generate_line_points(robot.state[0][0],robot.state[1][0], (nextWayPoint[0]+robot.state[0])/2,(nextWayPoint[1]+robot.state[1])/2)
#                 # else:
                    
                
#                 obsCircle = Circle(targetX,targetY,0.08,object[0])   
#                 inCollision, collisionPoint = obsCircle.is_in_collision_with_points(points)
                
#                 if inCollision:
#                     print(f"================WE ARE HITTING {object[0]}============ STOPPING")
#                     isInCollision = True
#                     collisionList.append([targetX,targetY])
#     if inCollision:
#         targetInView = False
    
#     return targetInView,targetCoord, collisionList, isInCollision, allFruitInView
                    

# def driveToPoint(targetName, wayPoint, robot_pose, goalPoint):
#     """function to drive the robot to the next way point
#             if there's an obstals in the way
#                 drive around it
            
#             if we see the target early and there's no obstals in the way
#                 discard future waypoints, drive to target

#     Args:
#         wayPoint (_type_): The desired way point
#     """
    
#     #calculating heading and distance
#     heading = get_angle_robot_to_goal(robot_pose,np.array(wayPoint))
#     distanceFromGoal = get_distance_robot_to_goal(robot_pose , np.array(wayPoint))
    
#     #defining constants
#     WHEEL_VEL  = 30
#     TIME_FULL_TURN = 5.8-0.065
#     STRAIGHT_WHEEL_VEL = 50
#     # TIME_1_METER = 12.3
#     TIME_1_METER = 7.5
    
#     turn_time = abs((heading)/(2*np.pi) * (TIME_FULL_TURN) )# replace with your calculation
#     drive_time = abs(distanceFromGoal*TIME_1_METER)
        
#     if(heading>0):
#         lv,rv = ppi.set_velocity([0, 1], turning_tick=WHEEL_VEL)
#     else:
#         lv,rv = ppi.set_velocity([0, -1], turning_tick=WHEEL_VEL)
        
    
#     startTime = time.time()
#     controlTime = time.time()
    
#     LMcollusion = False
#     unobstractedTarget=False
#     inCollusion = False
#     targetLastSeen = None

    
#     while time.time() -startTime <turn_time:
#         viewFromRobot = ppi.get_image()
#         landmarkPosition, landmarkCollisionList, LMInCollision,landMarkCoord = lookForLM(image=viewFromRobot)
#         targetInView, targetCoord, fruitCollisionList, fruitInCollision,allFruitInView = lookForFruit(targetName=targetName, image = viewFromRobot)
#         update_robot_state(controlTime,lv,rv,landmarkPosition)
#         controlTime = time.time()
        
#     ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot
#     lv,rv = ppi.set_velocity([1, 0], tick=STRAIGHT_WHEEL_VEL) #start driving foward
#     startTime = time.time()
#     controlTime = time.time()
    
#     targetInView = False
    
#     while time.time() -startTime <drive_time:
        
#         viewFromRobot = ppi.get_image()
#         landmarkPosition, landmarkCollisionList, LMInCollision,landMarkCoord = lookForLM(image=viewFromRobot,nextWayPoint=wayPoint)
#         targetInView, targetCoord, fruitCollisionList, fruitInCollision,allFruitInView = lookForFruit(targetName=targetName, image = viewFromRobot,nextWayPoint=wayPoint)
#         update_robot_state(controlTime,lv,rv,landmarkPosition)
#         controlTime = time.time()
        
#         if LMInCollision or fruitInCollision:
#             print("======STOPPING======= NEED TO GO A DIFFERENT WAY")
#             # ppi.set_velocity([0, 0], tick=WHEEL_VEL)
#             inCollusion = True
#             return unobstractedTarget, inCollusion, targetLastSeen
#             # break
#         else:
#             #in the case if we are not going to hit anything if we keep going
#             if targetInView == True:
                

                        
#                 #if the target is in view, and we are not hitting anything, we can go straight to the fruit
#                 # ppi.set_velocity([0, 0], tick=WHEEL_VEL)
#                 prepDis = math.sqrt((robot.state[0][0] - targetCoord[0])**2 + (robot.state[1][0] - targetCoord[1]) **2)
#                 offsetFromTruePos = math.sqrt((goalPoint[0] - targetCoord[0])**2 + (goalPoint[1] - targetCoord[1]) **2)
                
#                 if prepDis < 0.4:
#                     viewFromRobot = ppi.get_image()
#                     landmarkPosition, landmarkCollisionList, LMbeforeTarget,landMarkCoord = lookForLM(image=viewFromRobot,nextWayPoint = [targetCoord[0],targetCoord[1]])
#                     targetInView, targetCoord, fruitCollisionList, fruitBeforeTarget,allFruitInView = lookForFruit(targetName=targetName, image = viewFromRobot ,nextWayPoint = [targetCoord[0],targetCoord[1]])
                    
#                     if LMbeforeTarget== False and fruitBeforeTarget == False:
#                         print(f"\n\n\t =======NOW DRIVING TO TARGET=========")
#                         unobstractedTarget = True
#                         targetLastSeen = targetCoord
#                         return unobstractedTarget, inCollusion, targetLastSeen
#                 print(f"=========UNBSTRACTED TARGET AT {targetCoord}, {prepDis} AWAY going to target : {unobstractedTarget}=============, offset is {offsetFromTruePos}")

                    
                
#     return unobstractedTarget, inCollusion, targetLastSeen

# def driveToTarget(targetName, targetLastSeen):
#     """
#     Turn to face target
#         drive to target
#             if target not in view call drive to target
#             if collusion break
    

#     Args:
#         targetLastSeen (_type_): _description_
#     """
#         #reache
        
#     WHEEL_VEL  = 30
    
#     TIME_FULL_TURN = 5.8-0.065
#     TIME_1_METER = 12.3
#     FRUIT_TIMER = 5
#     facingTarget  = False
#     atTarget = False
#     image = ppi.get_image()
#     fruitLastSeenTime = time.time()
#     targetInView,targetCoord, collisionList, isInCollisio,allFruitInView = lookForFruit(targetName=targetName, image=image)
#     print(f"target in view is {targetInView}, target coord is {targetCoord}")
    
    
    
#     # input()
#     if targetInView:
#         targetLastSeen = targetCoord
#         fruitLastSeenTime = time.time()
        
    
#     while atTarget == False:
#         print("NOW DRIVING TO FRUIT")
        
#         if targetInView == False: #if we can't see the target, we start turning in the direction of where we last seen it
#             heading = get_angle_robot_to_goal(robot.state,np.array([targetLastSeen[0],targetLastSeen[1]]))
#             turn_time = abs((heading)/(2*np.pi) * (TIME_FULL_TURN) )
#             if(heading>0):
#                 lv,rv = ppi.set_velocity([0, 1], turning_tick=15)
#             else:
#                 lv,rv = ppi.set_velocity([0, -1], turning_tick=15)
                
#             startTime = time.time()
#             controlTime = time.time()
            
#             while abs(time.time() -startTime) <TIME_FULL_TURN*3: #*2 to allow buffer
#                 image = ppi.get_image()
#                 landmarkPosition, collisionList, isInCollision,landMarkCoord = lookForLM(image)
#                 update_robot_state(controlTime,lv,rv,landmarkPosition)
#                 controlTime = time.time()
#                 targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = image)
#                 if targetInView:
#                     targetLastSeen = targetCoord
#                     targetInView = True
#                     break
#             # ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot

#         #at this point we should be facing the target, now driving straight
#         lv,rv = ppi.set_velocity([1, 0], tick=WHEEL_VEL) #start driving foward
#         print("now driving towards target")

#         startTime = time.time()
#         controlTime = time.time()
        
#         while targetInView:
#             if time.time() - fruitLastSeenTime >10:
#                 #in the case if we haven't seen the fruit for more than 5 sec
#                 print("\n\n=========CAN'T LOCATE FRUIT=========\n\n")
#                 lv,rv = ppi.set_velocity([0, 0], tick=WHEEL_VEL)
#                 return False
#             image = ppi.get_image()
#             landmarkPosition, collisionList, isInCollision,landMarkCoord = lookForLM(image)
#             update_robot_state(controlTime,lv,rv,landmarkPosition)
#             controlTime = time.time()
#             targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = image)
#             if targetInView:
#                 prepDis = math.sqrt((robot.state[0][0] - targetCoord[0])**2 + (robot.state[1][0] - targetCoord[1]) **2)
#                 print(f"\n\n ===========TARGET {targetName} IN VIEW, {prepDis} AWAY=============")
#                 if prepDis < 0.3:
#                     ppi.set_velocity([0, 0], tick=WHEEL_VEL)
#                     atTarget = True
#                     return True
#                 if targetInView:
#                     targetLastSeen = targetCoord
#                     fruitLastSeenTime = time.time()
#             else:
#                 targetInView = False
#                 break
            
#         if time.time() - fruitLastSeenTime >15:
#             #in the case if we haven't seen the fruit for more than 5 sec
#             print("\n\n=========CAN'T LOCATE FRUIT=========\n\n")
#             lv,rv = ppi.set_velocity([0, 0], tick=WHEEL_VEL)
#             return False
            
# def addLocalPath(targetName,desiredWaypoint):
#     """
#     function that takes 3 photos and return all the obstals from these 3 photo
#     """
#     WHEEL_VEL = 30
#     TURNING_TIME = 0.5 #we turn for 0.5 second, take a pic
#     THRESHOLD = 0.1
    
#     obstaclesList = []
#     viewFromRobot = ppi.get_image()
#     landmarkPosition, collisionList, isInCollision,landMarkCoord = lookForLM(viewFromRobot,desiredWaypoint[0])
#     targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = viewFromRobot)
    
#     obstaclesList = obstaclesList +landMarkCoord
#     obstaclesList = obstaclesList + allFruitInView
#     initalAngle = robot.state[2][0]
#     lv,rv = ppi.set_velocity([0, 1], turning_tick=WHEEL_VEL)
#     startTime = time.time()
#     controlTime = time.time()
#     while time.time() -startTime <TURNING_TIME:
#         viewFromRobot = ppi.get_image()
#         LMcollusion,lmID,landmarkPosition,landMarkCoord = lookForLM(image=viewFromRobot)
#         update_robot_state(controlTime,lv,rv,landmarkPosition)
#         controlTime = time.time()
#         obstaclesList = obstaclesList +landMarkCoord
        
#     ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot
#     targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = viewFromRobot)
#     obstaclesList = obstaclesList + allFruitInView
    
#     lv,rv = ppi.set_velocity([0, -1], turning_tick=WHEEL_VEL)
#     startTime = time.time()
#     controlTime = time.time()
#     while time.time() -startTime <TURNING_TIME*2: 
#         viewFromRobot = ppi.get_image()
#         LMcollusion,lmID,landmarkPosition,landMarkCoord = lookForLM(image=viewFromRobot)
#         update_robot_state(controlTime,lv,rv,landmarkPosition)
#         controlTime = time.time()
#         obstaclesList = obstaclesList +landMarkCoord
#     ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot
#     targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = viewFromRobot)
#     obstaclesList = obstaclesList + allFruitInView
        
#     uniqueObstacles = []
    
#     print(f"list is {obstaclesList}")
    
#     for obstacles in obstaclesList:
#         if all(np.linalg.norm(np.array(obstacles) - np.array(uc)) > THRESHOLD for uc in uniqueObstacles):
#             uniqueObstacles.append(obstacles)
#     # plot_coordinates_with_radius([robot.state[0][0],robot.state[1][0]], desiredWaypoint ,obstaclesList)
#     selectedGoal = desiredWaypoint[0]
#     for i in range(0,len(desiredWaypoint)):
#         localPath,pos, G = plan_local_path_Astar((robot.state[0][0],robot.state[1][0]),robotAngle=initalAngle,goal=desiredWaypoint[i],obstacles_given=obstaclesList)
    
#         if localPath != None:
#             selectedGoal = desiredWaypoint[i]
#             break
        

#     localPath= []    
#     plotPath = [] 
#     try:
#         if localPath != None:
#             for j in localPath:
#                 plotPath.append((j[0],j[1]))
#     except:
#         localPath = []
        
#     # local_plot_single_path_and_obstacles(G,pos,plotPath,obstaclesList,(robot.state[0][0],robot.state[1][0]),selectedGoal)
    
#     # if len(localPath) == 0:
#     #     newRandomX = random.uniform(-0.1, 0.1)
#     #     newRandomY = random.uniform(-0.1, 0.1)
#     #     print(desiredWaypoint)
        

#     #     localPath.append([desiredWaypoint[0][0]+newRandomX, desiredWaypoint[0][1]+ newRandomY])
#     localPath.extend(desiredWaypoint[i:])
    
#     # formatPathPlot = []
#     # for i in localPath:
#     #     formatPathPlot.append((i[0],i[1]))
        
#     # print(localPath)
#     # input()
    
#     # local_plot_single_path_and_obstacles(G,pos,formatPathPlot,obstaclesList,(robot.state[0][0],robot.state[1][0]),selectedGoal)
    
#     return localPath
    

    
    
# def plot_coordinates_with_radius(robotPosition, desiredWaypoint, coordinates, radius=0.08):
#     # Create a plot
#     fig, ax = plt.subplots(figsize=(10,10))
#     square = plt.Rectangle((-1.5, -1.5), 3, 3, fill=False, color='red', label="3x3 Box at Origin")
#     plt.gca().add_patch(square)

#     # Plot each coordinate as a scatter point
#     for coord in coordinates:
#         # Plot the scatter point
#         ax.scatter(*coord, color='blue')

#         # Add a circle around the scatter point with the specified radius
#         circle = plt.Circle(coord, radius, color='blue', fill=False, linestyle='--')
#         ax.add_patch(circle)

#     # Set equal scaling for both axes
    
#     robotCircle = plt.Circle(robotPosition, 0.15, color='red', fill=False, linestyle='--')
#     ax.add_patch(robotCircle)
    
#     goalCircle = plt.Circle(desiredWaypoint, 0.15, color='green', fill=False, linestyle='--')
#     ax.add_patch(goalCircle)
    
#     ax.set_aspect('equal', adjustable='box')

#     # Add grid and labels
#     plt.grid(True)
#     plt.xlabel('X')
#     plt.ylabel('Y')

#     # Show the plot
#     plt.show()
                
# def findClosestObs(listOfAllObs):
#     #find the closest obs from the robot, and return a point that can avoid this
#     #Input: list of all obs that we will be hitting
#     #output: next way point that can avoid hitting the closest obs [x,y]
    
#     collisionCoord = None
#     minDis = 999
#     DIS_FROM_OBS = 0.4 #the distance left/right of the obstals the next way point should be
    
#     for i in listOfAllObs:
#         prepDis =  math.sqrt((robot.state[0][0] - i[0])**2 + (robot.state[1][0] - i[1]) **2)
#         if prepDis < minDis:
#             minDis = prepDis
#             collisionCoord = [i[0],i[1]]
            
#     if collisionCoord != None:
#         xNew = DIS_FROM_OBS*np.cos(180-robot[2][0]) + collisionCoord[0]
#         yNew = DIS_FROM_OBS*np.sin(180-robot[2][0]) + collisionCoord[0]
        
#     return xNew,yNew
    
    
    
            

# def startNavV2(trueMap, shoppingList):
    
#     allFruitFound  = False
#     targetIdx = 0
#     while allFruitFound == False:
#         currentTarget = shoppingList[targetIdx]
        
#         formattedTarget = currentTarget.split('_')[0]
#         foundFruit = False
        

        
#         needNewPath = True
#         goalPoint = (trueMap.get(currentTarget).get('x'),trueMap.get(currentTarget).get('y'))
#         arriveAtTarget = False
#         wayPointIdx = 0
        
        
#         while foundFruit == False:
#             if needNewPath:
#                 currentPose = (robot.state[0][0],robot.state[1][0])
#                 findingPath = True
#                 lastWayPointIdx = -1
#                 pathPlannerTimeLimter = 10
#                 pathPos = 0
#                 while findingPath:
                    
#                     # optimisedGoal = find_optimal_goal_point(trueMap, currentPose , goalPoint, 0.2, grid_resolution=100)
#                     # print(optimisedGoal)
#                     # newPath,pos, G   = plan_path_Astar(currentPose,goalPoint,trueMap,pathPlannerTimeLimter)
#                     newPath,pos, G   = plan_path_Astar(currentPose,goalPoint,trueMap,pathPlannerTimeLimter)
                    
#                     print('trying to find a path')
                    
#                     if newPath == None:                
#                         currentPose = (0,0)
#                         # print(path[-1-pathPos])
#                         # input(f"going backward, full path is {path}")
#                         # unobstractedTarget, inCollusion,targetLastSeen = driveToPoint(formattedTarget,path[-1-pathPos],robot.state,goalPoint)
#                         # pathPos+= 1
#                         # lv,rv = ppi.set_velocity([0, 0], tick=30)
#                         # currentPose = (path[-1][0],path[-1][1])
                        
#                         if(pathPlannerTimeLimter)>4:
#                             pathPlannerTimeLimter-=0.5
#                     else:
#                         # newPath = [[0,0],[0.5,0],[1,0],[0,0]]
#                         path = newPath
                        
#                         findingPath = False
#                         path.pop(0)
                    
                    
#                 plotCurrentPath(trueMap,G,pos,path,currentPose,goalPoint)
#                 needNewPath = False
#                 lastWayPoint = True
#                 wayPointIdx = 0
                
            
#             # path = [[0,0],[1,0],[0,0]]
#             nextWayPoint = path[wayPointIdx]
#             wayPointIdx += 1
#             unobstractedTarget, inCollusion,targetLastSeen = driveToPoint(formattedTarget,nextWayPoint,robot.state,goalPoint)
            
#             if inCollusion:
#                 if len(path[wayPointIdx :]) == 0:
#                     updatedPath = addLocalPath(formattedTarget,[goalPoint])
                
#                 else:
#                     updatedPath = addLocalPath(formattedTarget,path[wayPointIdx :])
#                 # print(updatedPath)
#                 updatedPath.pop(0)
#                 path = updatedPath
#                 wayPointIdx = 0
            
            
#             elif unobstractedTarget == True:
#                 ppi.set_velocity([0, 0], tick=30) 
#                 # input("calling drive to target from unobstracted")
#                 if len(targetLastSeen)== 0:
#                     targetLastSeen = goalPoint
#                 arriveAtTarget = driveToTarget(formattedTarget, targetLastSeen)
                
#                 if arriveAtTarget == True:
#                     print("======ARRIVE AT TARGET========")
#                     foundFruit = True
#                     targetIdx+=1
#                     time.sleep(2)
#                     break
#                 else:
#                     needNewPath = True
#                     unobstractedTarget = False
#                     break
                    
                
                
#             if wayPointIdx == len(path):
#                 if targetLastSeen == None:
#                     targetLastSeen = goalPoint
#                 arriveAtTarget = driveToTarget(formattedTarget, targetLastSeen)
                
#                 if arriveAtTarget == True:
#                     print("======ARRIVE AT TARGET========")
#                     foundFruit = True
#                     targetIdx += 1
#                     time.sleep(2)
#                     break
                
#                 else:
#                     needNewPath = True

#             ppi.set_velocity([0, 0], tick=30)    
        
#         if currentTarget == shoppingList[-1]:
#             print("\n\nGOT ALL FRUIT JOB DONE \n\n")
#             break
    
    
    
    



# if __name__ == "__main__":
    
#     parser = argparse.ArgumentParser("Fruit searching")
#     parser.add_argument("--map", type=str, default='est_maps/estMap1.txt') # change to 'M4_true_map_part.txt' for lv2&3
#     parser.add_argument("--ip", metavar='', type=str, default='192.168.50.1')
#     parser.add_argument("--port", metavar='', type=int, default=8080)
#     args, _ = parser.parse_known_args()
    
    
#     fileS = "calibration/param/scale.txt"
#     scale = np.loadtxt(fileS, delimiter=',')
#     fileB = "calibration/param/baseline.txt"
#     baseline = np.loadtxt(fileB, delimiter=',')
#     fileC = "calibration/param/intrinsic.txt"
#     camera_matrix = np.loadtxt(fileC, delimiter=',')
#     fileD = "calibration/param/distCoeffs.txt"
#     dist_coeffs = np.loadtxt(fileD, delimiter=',')
    
#     script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)
    
#     model_path = f'{script_dir}/YOLO/model/best.pt'
#     yolo = Detector(model_path)

#     ppi = PenguinPi(args.ip,args.port)
#     ppi.set_velocity([0, 0], tick= 30)
#     robot = Robot(baseline,scale,camera_matrix,dist_coeffs)
#     ekf = EKF(robot)
#     control_clock = time.time()
#     aruco_det = aruco.aruco_detector(robot,marker_length=0.07) #initalise the aruco detector

#     trueMap = read_true_map(args.map)
#     search_list = read_search_list()

#     print(f"=========== search list=======\n\t{search_list}")
#     for i in range(len(search_list)):
#         print(search_list[i])
#         search_list[i] = search_list[i]+"_0"
#         target_pose_dict = {}
#         detected_type_list = []
    
    
#     autoNav = input("AUTO NAV [Y/N] ")
    
#     if autoNav:
#         startNavV2(trueMap, search_list)
        
        







import sys, os
import cv2
import numpy as np
import json
import argparse
import time
import pandas


import random

# import SLAM components
sys.path.insert(0, "{}/slam".format(os.getcwd()))
from ekfNoLM import EKF
from slam.robot import Robot
import slam.aruco_detector as aruco


# import utility functions
sys.path.insert(0, "util")
from util.pibot import PenguinPi
import util.measure as measure


from YOLO.detector import Detector
import pathPlannerV2
from Obstacle import *
from math_functions import *
from path_find_with_weight import *
from localPathPlanner import *
from Obstacle import *


def celebrate():
    print('''
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⡿⠳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⡶⠶⢖⠦⣄⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣷⡀⠀⠀⠀⠀⠀⠐⠋⠉⠉⠛⢷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠟⠁⠀⠀⢀⠇⠈⢳⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡿⠋⠀⠀⠀⢀⣀⣠⠤⠤⠤⠤⠤⠤⠤⢌⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⢻⠀⠀⠀⠀⠈⠀⠀⢸⠇⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠁⣠⠤⠒⣋⡭⠤⠒⠒⠉⠉⡩⢟⣣⣤⣀⡢⣬⣉⠒⠤⣄⠀⠀⠀⠀⠀⠀⠀⠀⢼⠈⠃⠀⠀⠀⠀⠀⠀⡞⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠖⣉⠴⠒⠉⠀⠀⠀⠀⠀⢀⣞⣴⠟⠋⠉⠛⢿⣾⣎⠑⢤⡀⠙⠢⣄⠀⠀⠀⠀⠀⠸⡄⠀⠀⠀⠀⠀⠀⣸⠃⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⢋⡤⢊⣁⡀⠀⠀⠀⠀⠀⠀⠀⣞⣾⠃⠀⠀⠀⠀⠀⠹⣿⡄⠀⠱⡄⠀⠈⠑⣄⠀⠀⢀⣠⣽⠶⠶⠶⠒⠒⠒⠛⢤⣄⡀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠋⡴⢋⢔⣭⣴⣿⣷⣤⠀⠀⠀⠀⠰⣽⠃⠀⠀⠀⠀⠀⠀⠀⢹⣇⠀⠀⠘⡄⠀⠀⠈⢳⣶⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠯⠻⣦⡀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡜⢡⠎⢠⢯⣿⠋⠁⠀⠈⠻⣷⠀⠀⠀⠀⡏⠀⠀⠀⠐⢷⢶⣄⠀⠀⣿⠀⠀⠐⠁⠀⠀⢰⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠪⠙⣆⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡞⢠⠃⠀⣮⡿⠁⠀⠀⠀⠀⠀⠻⣇⠀⠀⢸⡇⠀⠀⢀⠀⣸⣷⣻⡄⠀⣿⠀⠀⠀⠀⠀⠀⣏⠓⠒⢀⣀⣀⣀⣀⣀⣀⣀⣀⠀⢠⠖⠀⠀⠀⠘⡄
            ⠀⠀⣀⣠⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡞⢀⠇⠀⢰⣿⠇⠀⠀⠀⠀⠶⣶⡄⢹⠀⠀⠀⡇⠀⠀⣾⢹⣿⣿⣏⡇⠀⣿⠀⠀⣀⣤⡤⠤⣼⣶⠿⠛⠉⠀⠀⠀⠀⠀⠀⠉⠙⡇⠀⠀⠀⠀⠀⠀
            ⣠⢾⠋⠀⠀⠈⠻⡷⣄⠀⠀⠀⠀⠀⠀⢰⠁⠸⠀⠀⠸⣿⠀⠀⠀⠀⣄⣀⣷⣽⣸⠀⠀⠀⣇⠀⠀⠸⣞⣿⣅⣽⠁⢀⣇⣴⠞⠋⠁⠀⣼⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠇⠀⠀⠀⠀⠀⠀
            ⡇⠘⠂⠀⠀⠀⠀⠁⠘⡆⠀⠀⠀⠀⠀⡏⠀⠀⠀⠀⢰⣿⠀⠀⠀⠀⣇⣿⣿⣿⣿⠀⠀⠀⠸⡄⠀⠀⠙⠧⠽⠃⠀⡼⠋⠀⠀⠀⠀⠀⣯⠦⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀
            ⢳⡀⠀⠀⠀⠀⠀⠀⢀⣹⣤⣤⣤⣤⣄⡇⠀⠰⠀⠀⠀⣿⠀⠀⠀⠀⢻⡽⠿⣾⢹⠀⠀⠀⠀⠻⡄⠀⠀⠀⠀⢠⠞⠁⠀⣀⣀⡀⠀⠀⠘⢧⡀⣠⣤⡶⠖⠛⠛⠛⠒⠒⡞⠀⠀⠀⠀⠀⠀⢀⠀
            ⠀⠉⠳⣄⠀⢀⡤⡺⠛⠉⠀⠀⠀⠀⠈⣻⢦⠀⠀⠀⠀⢻⡆⠀⠀⠀⠈⠻⠟⢁⡎⠀⠀⠀⠀⠀⠙⠦⣄⣀⣤⠟⠀⠀⠉⣀⣀⣀⡉⠂⠀⠀⣽⣏⠁⠀⠀⠀⠀⠀⠀⠀⢇⠀⠀⠀⠀⠀⢠⡞⠀
            ⠀⠀⠀⢈⣷⠋⠀⠁⠀⠀⠀⠀⠀⢈⣩⣤⣼⣧⣤⡀⠀⠀⠻⡄⠀⠀⠀⠀⢀⡼⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠋⠀⠀⣈⣭⠵⠒⠋⠉⠂⠀⠀⠹⡌⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⠋⠀⠀
            ⠀⠀⠀⣾⠋⠀⠀⠀⠀⠀⢀⡤⠞⠉⠉⠀⠀⠀⠈⣻⡆⠀⣀⣙⡦⠤⣀⣤⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⠴⠋⣡⡏⠀⠀⠀⠀⠀⠀⠀⠀⠙⠲⣄⡀⠀⠀⠀⠀⠀⠀⣀⣠⠴⠋⠁⠀⠀⠀
            ⠀⠀⢸⠇⠀⠀⠀⠀⢀⡶⠉⠀⠀⠀⠀⠀⠀⠀⠈⠁⡧⠋⠉⠁⠀⠀⠀⠘⠀⠀⠀⠀⠀⠀⠀⢀⣠⠴⠚⠉⠀⢀⣴⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠁⠈⠉⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⢸⠀⠀⠀⠉⠑⢏⠀⠀⠀⠀⠀⠀⣀⣤⠶⠶⠾⣧⡀⠀⠀⠀⠀⠀⣤⣤⣤⣤⡤⠒⠒⠉⠁⠀⠀⣀⣤⣶⠿⢿⡿⠀⠀⠀⠀⠀⠀⠀⠀⢀⡶⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⠈⡆⠀⠀⠀⠀⠈⠇⠀⠀⢀⡤⠚⠉⠀⠀⠀⠐⠁⡇⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣶⣶⣶⣶⣾⠿⣿⡟⠁⠀⣼⠃⠀⠀⠀⠀⠀⣠⠞⣠⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠹⡄⠀⠀⠀⠀⠀⠀⠉⠻⡄⠀⠀⠀⠀⠀⠀⣰⠁⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⠃⣠⠏⠀⠀⣰⠏⠀⠀⠀⠀⠠⠞⢁⡴⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠙⣄⠀⠀⠀⠀⠀⠀⠀⠊⠀⠀⠀⠀⢀⡴⠋⠳⢄⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⠁⠊⠀⠀⢀⡰⠋⠀⠀⠀⠀⠀⣠⡴⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠈⠑⠦⣀⡀⠀⠀⠀⠀⠀⣀⡠⠖⠋⠀⠀⠀⠀⠙⠢⢄⡀⠀⠀⠀⠀⠈⠛⢿⣇⣀⣀⣠⠴⠋⠀⠀⠀⢀⣀⠤⠚⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠒⠒⠚⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠒⠤⢤⣀⣀⣀⣀⣀⣀⣀⣀⡠⠤⠖⠚⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
          ''')  

def get_angle_robot_to_goal(robot_state, goal):
    if goal.shape[0] < 3:
        goal = np.hstack((goal, np.array([0])))

    x_goal, y_goal,_ = goal

    x, y, theta = robot_state
    x_diff = x_goal - x
    y_diff = y_goal - y

    alpha = clamp_angle(np.arctan2(y_diff, x_diff) - theta)
    return alpha

def clamp_angle(rad_angle=0, min_value=-np.pi, max_value=np.pi):
	"""
	Restrict angle to the range [min, max]
	:param rad_angle: angle in radians
	:param min_value: min angle value
	:param max_value: max angle value
	"""

	if min_value > 0:
		min_value *= -1

	angle = (rad_angle + max_value) % (2 * np.pi) + min_value

	return angle

def get_distance_robot_to_goal(robot_state=np.zeros(3), goal=np.zeros(3)):
	"""
	Compute Euclidean distance between the robot and the goal location
	:param robot_state: 3D vector (x, y, theta) representing the current state of the robot
	:param goal: 3D Cartesian coordinates of goal location
	"""

	if goal.shape[0] < 3:
		goal = np.hstack((goal, np.array([0])))

	x_goal, y_goal,_ = goal
	x, y,_ = robot_state
	x_diff = x_goal - x
	y_diff = y_goal - y

	rho = np.hypot(x_diff, y_diff)

	return rho

def generate_line_points(x, y, xEnd, yEnd, n_points=10):
    # Calculate the step size for x and y directions
    x_step = (xEnd - x) / (n_points - 1)
    y_step = (yEnd - y) / (n_points - 1)

    # Generate the points
    points = []
    for i in range(n_points):
        new_x = x + i * x_step
        new_y = y + i * y_step
        points.append((new_x, new_y))
    
    return points
     
def update_robot_state(controlTime, lv, rv, landmarkPosition):
    drive_meas = control(controlTime,lv,rv)
    update_slam(drive_meas,landmarkPosition)
    
def update_slam(drive_meas, lms):
    
    ekf.predict(drive_meas)
    ekf.add_landmarks(lms)
    ekf.update(lms)
    
def control(control_clock,lv,rv):
    # lv,rv = ppi.set_velocity(driveCommand, wheel_vel)
    dt = time.time() - control_clock
    drive_meas = measure.Drive(lv,-rv,dt)
    control_clock = time.time()
    
    return drive_meas
    
def estimate_pose(camera_matrix, obj_info, robot_pose):
    """
    function:
        estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
    input:
        camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
            |f_x, s,   c_x|
            |0,   f_y, c_y|
            |0,   0,   1  |
            (f_x, f_y): focal length in pixels
            (c_x, c_y): optical centre in pixels
            s: skew coefficient (should be 0 for PenguinPi)
        obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
        robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
    output:
        target_pose: dict, prediction of target pose
    """
    # read in camera matrix (from camera calibration results)
    focal_length = camera_matrix[0][0]

    # there are 8 possible types of fruits and vegs
    ######### Replace with your codes #########
    # TODO: measure actual sizes of targets [width, depth, height] and update the dictionary of true target dimensions
    target_dimensions_dict = {'pear': [156,151,0.0914], 'lemon': [1.0,1.0,0.0527], 
                              'lime': [1.0,1.0,0.053], 'tomato': [1.0,1.0,0.058], 
                              'capsicum': [1.0,1.0,0.0963], 'potato': [1.0,1.0,0.0563], 
                              'pumpkin': [1.0,1.0,0.074], 'garlic': [1.0,1.0,0.0713],'orange': [1, 1, 79]}
    #########

    # estimate target pose using bounding box and robot pose
    target_class = obj_info[0]     # get predicted target label of the box
    target_box = obj_info[1]       # get bounding box measures: [x,y,width,height]
    true_height = target_dimensions_dict[target_class][2]   # look up true height of by class label

    # compute pose of the target based on bounding box info, true object height, and robot's pose
    pixel_height = target_box[3]
    pixel_center = target_box[0]
    distance = true_height/pixel_height * focal_length  # estimated distance between the robot and the centre of the image plane based on height
    # training image size 320x240p
    image_width = 320 # change this if your training image is in a different size (check details of pred_0.png taken by your robot)
    x_shift = image_width/2 - pixel_center              # x distance between bounding box centre and centreline in camera view
    theta = np.arctan(x_shift/focal_length)     # angle of object relative to the robot
    ang = theta + robot_pose[2]     # angle of object in the world frame
    
   # relative object location
    distance_obj = distance/np.cos(theta) # relative distance between robot and object
    x_relative = distance_obj * np.cos(theta) # relative x pose
    y_relative = distance_obj * np.sin(theta) # relative y pose
    relative_pose = {'x': x_relative, 'y': y_relative}
    #print(f'relative_pose: {relative_pose}')

    # location of object in the world frame using rotation matrix
    delta_x_world = x_relative * np.cos(robot_pose[2]) - y_relative * np.sin(robot_pose[2])
    delta_y_world = x_relative * np.sin(robot_pose[2]) + y_relative * np.cos(robot_pose[2])
    # add robot pose with delta target pose
    target_pose = {'y': (robot_pose[1]+delta_y_world)[0],
                   'x': (robot_pose[0]+delta_x_world)[0]}
    #print(f'delta_x_world: {delta_x_world}, delta_y_world: {delta_y_world}')
    #print(f'target_pose: {target_pose}')

    return target_pose


def plotCurrentPath(obstacles_default,G,pos,path,start_point,goal_point):
    formatPathPlot = []
    obstaclesList = []
    radius = 0.12
    for key,value in obstacles_default.items():
        xCoord = value.get('x')
        yCoord = value.get('y')
        obstaclesList.append(Circle(xCoord, yCoord, radius=radius, name=key))        

    for i in path:
        formatPathPlot.append((i[0],i[1]))
        
    plot_single_path_and_obstacles(G,pos,formatPathPlot,obstaclesList,start_point,goal_point)
    

def lookForLM(image, nextWayPoint = None):
    """Function that look for landmark in view of the robot
            if nextWayPoint is None, 
                we are turning, don't need to check collusio

    Args:
        nextWayPoint (_type_, optional): _description_. Defaults to None.
        if it is None:
            we are turning, so no collision checking needed
        else:
            we are going straight, need to check if we are going to hit anything
        
        outputs:
            landmark : List of landmarks for updating position
            isInCollision (bool): true if we are in collision
            collisionPos: List of [x,y] of things that we are going to hit
    """
    COLLISION_DIS = 0.7
    OBS_RADIUS = 0.1
    
    isInCollision = False
    collisionList = [] #list of coordiant that the robot will go into
    landMarkCoord = []
    landmarkPosition,_ = aruco_det.detect_marker_positions(image)
    
    if nextWayPoint != None:
        disToWaypoint = math.sqrt((nextWayPoint[0]-robot.state[0][0])**2 + (nextWayPoint[1]-robot.state[1][0])**2)
        
        if disToWaypoint > COLLISION_DIS: #we won't look beyond 0.2m for collision
            points = generate_line_points(robot.state[0],robot.state[1], (nextWayPoint[0]+robot.state[0])/2,(nextWayPoint[1]+robot.state[1])/2)
        else:
            points = generate_line_points(robot.state[0],robot.state[1], nextWayPoint[0],nextWayPoint[1])
        
        for landmark in landmarkPosition:
            gobalLM = ekf.compute_gobal_marker(landmark)
            obsCircle = Circle(gobalLM[0][0],gobalLM[1][0],OBS_RADIUS,landmark.tag)
            inCollision, collisionPoint = obsCircle.is_in_collision_with_points(points)
            landMarkCoord.append([gobalLM[0][0],gobalLM[1][0]])
            if inCollision:
                collisionList.append([gobalLM[0][0] , gobalLM[1][0]])
                isInCollision = True
    else:
        return landmarkPosition, collisionList, isInCollision,landMarkCoord
    
    return landmarkPosition, collisionList, isInCollision,landMarkCoord
        
  
def lookForFruit(targetName, image, nextWayPoint = None):
    """Function that look for fruit in the view of the robot
        if it sees an fruit in the way of the robot
            return list of collision points
        
        if there's no fruit in the view of the robot
            if it sees the target in view 
                check if the target is around where we expect it to be
                    if it is within a radius from true map, it is the target
                    
        if nextWayPoint is None, we are turning
            if we see the target, 
            
    Args:
        image (_type_): _description_
        nextWayPoint (_type_, optional): _description_. Defaults to None.
    """
    
    # targetName = search_list[0].split('_')[0]
    targetInView = False
    isInCollision = False
    inCollision = False
    collisionList = []
    targetCoord = []
    allFruitInView = [] #coord of all the fruit in view
                
    yolo_input_img = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    detector_output, yolo_vis = yolo.detect_single_image(yolo_input_img)
    

    for object in detector_output:
        print(f"========seeing {object[0]} target is {targetName}")
        targetPose  = estimate_pose(camera_matrix, object, ekf.robot.state)
        targetX = targetPose.get('x')
        targetY = targetPose.get('y')
        allFruitInView.append([targetX,targetY])
        
        if object[0] == targetName:
            #checking if it is the real target
            targetInView = True
            targetCoord = [targetX,targetY]
        else: # if we are seeing the target, don't need to check collusion
            if nextWayPoint != None:
                #since we are going straight, we need to check what's in front of us
                
                disToWaypoint = math.sqrt((nextWayPoint[0]-robot.state[0])**2 + (nextWayPoint[1]-robot.state[1])**2)
                #if the next way point is too far away, we don't need to check collusion
                points = generate_line_points(robot.state[0][0],robot.state[1][0], nextWayPoint[0],nextWayPoint[1])
                # if disToWaypoint > 0.2:
                #     points = generate_line_points(robot.state[0][0],robot.state[1][0], (nextWayPoint[0]+robot.state[0])/2,(nextWayPoint[1]+robot.state[1])/2)
                # else:
                    
                
                obsCircle = Circle(targetX,targetY,0.08,object[0])   
                inCollision, collisionPoint = obsCircle.is_in_collision_with_points(points)
                
                if inCollision:
                    print(f"================WE ARE HITTING {object[0]}============ STOPPING")
                    isInCollision = True
                    collisionList.append([targetX,targetY])
    if inCollision:
        targetInView = False
    
    return targetInView,targetCoord, collisionList, isInCollision, allFruitInView
                    

def driveToPoint(targetName, wayPoint, robot_pose, goalPoint):
    """function to drive the robot to the next way point
            if there's an obstals in the way
                drive around it
            
            if we see the target early and there's no obstals in the way
                discard future waypoints, drive to target

    Args:
        wayPoint (_type_): The desired way point
    """
    
    #calculating heading and distance
    heading = get_angle_robot_to_goal(robot_pose,np.array(wayPoint))
    distanceFromGoal = get_distance_robot_to_goal(robot_pose , np.array(wayPoint))
    
    #defining constants
    WHEEL_VEL  = 30
    TIME_FULL_TURN = 5.8-0.065
    STRAIGHT_WHEEL_VEL = 50
    # TIME_1_METER = 12.3
    TIME_1_METER = 7.5
    
    turn_time = abs((heading)/(2*np.pi) * (TIME_FULL_TURN) )# replace with your calculation
    drive_time = abs(distanceFromGoal*TIME_1_METER)
        
    if(heading>0):
        lv,rv = ppi.set_velocity([0, 1], turning_tick=WHEEL_VEL)
    else:
        lv,rv = ppi.set_velocity([0, -1], turning_tick=WHEEL_VEL)
        
    
    startTime = time.time()
    controlTime = time.time()
    
    LMcollusion = False
    unobstractedTarget=False
    inCollision = False
    targetLastSeen = None

    
    while time.time() -startTime <turn_time:
        viewFromRobot = ppi.get_image()
        landmarkPosition, landmarkCollisionList, LMInCollision,landMarkCoord = lookForLM(image=viewFromRobot)
        targetInView, targetCoord, fruitCollisionList, fruitInCollision,allFruitInView = lookForFruit(targetName=targetName, image = viewFromRobot)
        update_robot_state(controlTime,lv,rv,landmarkPosition)
        controlTime = time.time()
        
    ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot
    lv,rv = ppi.set_velocity([1, 0], tick=STRAIGHT_WHEEL_VEL) #start driving foward
    startTime = time.time()
    controlTime = time.time()
    
    targetInView = False
    
    while time.time() -startTime <drive_time:
        
        viewFromRobot = ppi.get_image()
        landmarkPosition, landmarkCollisionList, LMInCollision,landMarkCoord = lookForLM(image=viewFromRobot,nextWayPoint=wayPoint)
        targetInView, targetCoord, fruitCollisionList, fruitInCollision,allFruitInView = lookForFruit(targetName=targetName, image = viewFromRobot,nextWayPoint=wayPoint)
        update_robot_state(controlTime,lv,rv,landmarkPosition)
        controlTime = time.time()
        
        if LMInCollision or fruitInCollision:
            print("======STOPPING======= NEED TO GO A DIFFERENT WAY")
            # ppi.set_velocity([0, 0], tick=WHEEL_VEL)
            inCollision = True
            return unobstractedTarget, inCollision, targetLastSeen
            # break
        else:
            #in the case if we are not going to hit anything if we keep going
            if targetInView == True:
                

                        
                #if the target is in view, and we are not hitting anything, we can go straight to the fruit
                # ppi.set_velocity([0, 0], tick=WHEEL_VEL)
                prepDis = math.sqrt((robot.state[0][0] - targetCoord[0])**2 + (robot.state[1][0] - targetCoord[1]) **2)
                offsetFromTruePos = math.sqrt((goalPoint[0] - targetCoord[0])**2 + (goalPoint[1] - targetCoord[1]) **2)
                
                if prepDis < 0.4:
                    viewFromRobot = ppi.get_image()
                    landmarkPosition, landmarkCollisionList, LMbeforeTarget,landMarkCoord = lookForLM(image=viewFromRobot,nextWayPoint = [targetCoord[0],targetCoord[1]])
                    targetInView, targetCoord, fruitCollisionList, fruitBeforeTarget,allFruitInView = lookForFruit(targetName=targetName, image = viewFromRobot ,nextWayPoint = [targetCoord[0],targetCoord[1]])
                    
                    if LMbeforeTarget== False and fruitBeforeTarget == False:
                        print(f"\n\n\t =======NOW DRIVING TO TARGET=========")
                        unobstractedTarget = True
                        targetLastSeen = targetCoord
                        return unobstractedTarget, inCollision, targetLastSeen
                print(f"=========UNBSTRACTED TARGET AT {targetCoord}, {prepDis} AWAY going to target : {unobstractedTarget}=============, offset is {offsetFromTruePos}")

                    
                
    return unobstractedTarget, inCollision, targetLastSeen

def driveToTarget(targetName, targetLastSeen):
    """
    Turn to face target
        drive to target
            if target not in view call drive to target
            if collusion break
    

    Args:
        targetLastSeen (_type_): _description_
    """
        #reache
        
    WHEEL_VEL  = 30
    
    TIME_FULL_TURN = 5.8-0.065
    TIME_1_METER = 12.3
    FRUIT_TIMER = 5
    facingTarget  = False
    atTarget = False
    image = ppi.get_image()
    fruitLastSeenTime = time.time()
    targetInView,targetCoord, collisionList, isInCollisio,allFruitInView = lookForFruit(targetName=targetName, image=image)
    print(f"target in view is {targetInView}, target coord is {targetCoord}")
    
    
    
    # input()
    if targetInView:
        targetLastSeen = targetCoord
        fruitLastSeenTime = time.time()
        
    
    while atTarget == False:
        print("NOW DRIVING TO FRUIT")
        
        if targetInView == False: #if we can't see the target, we start turning in the direction of where we last seen it
            heading = get_angle_robot_to_goal(robot.state,np.array([targetLastSeen[0],targetLastSeen[1]]))
            turn_time = abs((heading)/(2*np.pi) * (TIME_FULL_TURN) )
            if(heading>0):
                lv,rv = ppi.set_velocity([0, 1], turning_tick=15)
            else:
                lv,rv = ppi.set_velocity([0, -1], turning_tick=15)
                
            startTime = time.time()
            controlTime = time.time()
            
            while abs(time.time() -startTime) <TIME_FULL_TURN*3: #*2 to allow buffer
                image = ppi.get_image()
                landmarkPosition, collisionList, isInCollision,landMarkCoord = lookForLM(image)
                update_robot_state(controlTime,lv,rv,landmarkPosition)
                controlTime = time.time()
                targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = image)
                if targetInView:
                    targetLastSeen = targetCoord
                    targetInView = True
                    break
            # ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot

        #at this point we should be facing the target, now driving straight
        lv,rv = ppi.set_velocity([1, 0], tick=WHEEL_VEL) #start driving foward
        print("now driving towards target")

        startTime = time.time()
        controlTime = time.time()
        
        while targetInView:
            if time.time() - fruitLastSeenTime >10:
                #in the case if we haven't seen the fruit for more than 5 sec
                print("\n\n=========CAN'T LOCATE FRUIT=========\n\n")
                lv,rv = ppi.set_velocity([0, 0], tick=WHEEL_VEL)
                return False
            image = ppi.get_image()
            landmarkPosition, collisionList, isInCollision,landMarkCoord = lookForLM(image)
            update_robot_state(controlTime,lv,rv,landmarkPosition)
            controlTime = time.time()
            targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = image)
            if targetInView:
                prepDis = math.sqrt((robot.state[0][0] - targetCoord[0])**2 + (robot.state[1][0] - targetCoord[1]) **2)
                print(f"\n\n ===========TARGET {targetName} IN VIEW, {prepDis} AWAY=============")
                if prepDis < 0.31:
                    ppi.set_velocity([0, 0], tick=WHEEL_VEL)
                    atTarget = True
                    return True
                if targetInView:
                    targetLastSeen = targetCoord
                    fruitLastSeenTime = time.time()
            else:
                targetInView = False
                break
            
        if time.time() - fruitLastSeenTime >15:
            #in the case if we haven't seen the fruit for more than 5 sec
            print("\n\n=========CAN'T LOCATE FRUIT=========\n\n")
            lv,rv = ppi.set_velocity([0, 0], tick=WHEEL_VEL)
            return False
            
def addLocalPath(targetName,desiredWaypoint):
    """
    function that takes 3 photos and return all the obstals from these 3 photo
    """
    WHEEL_VEL = 30
    TURNING_TIME = 0.5 #we turn for 0.5 second, take a pic
    THRESHOLD = 0.1
    
    obstaclesList = []
    viewFromRobot = ppi.get_image()
    landmarkPosition, collisionList, isInCollision,landMarkCoord = lookForLM(viewFromRobot,desiredWaypoint[0])
    targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = viewFromRobot)
    
    obstaclesList = obstaclesList +landMarkCoord
    obstaclesList = obstaclesList + allFruitInView
    initalAngle = robot.state[2][0]
    lv,rv = ppi.set_velocity([0, 1], turning_tick=WHEEL_VEL)
    startTime = time.time()
    controlTime = time.time()
    while time.time() -startTime <TURNING_TIME:
        viewFromRobot = ppi.get_image()
        LMcollusion,lmID,landmarkPosition,landMarkCoord = lookForLM(image=viewFromRobot)
        update_robot_state(controlTime,lv,rv,landmarkPosition)
        controlTime = time.time()
        obstaclesList = obstaclesList +landMarkCoord
        
    ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot
    targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = viewFromRobot)
    obstaclesList = obstaclesList + allFruitInView
    
    lv,rv = ppi.set_velocity([0, -1], turning_tick=WHEEL_VEL)
    startTime = time.time()
    controlTime = time.time()
    while time.time() -startTime <TURNING_TIME*2: 
        viewFromRobot = ppi.get_image()
        LMcollusion,lmID,landmarkPosition,landMarkCoord = lookForLM(image=viewFromRobot)
        update_robot_state(controlTime,lv,rv,landmarkPosition)
        controlTime = time.time()
        obstaclesList = obstaclesList +landMarkCoord
    ppi.set_velocity([0, 0], tick=WHEEL_VEL) #stopping the robot
    targetInView,targetCoord, collisionList, isInCollision,allFruitInView = lookForFruit(targetName=targetName,image = viewFromRobot)
    obstaclesList = obstaclesList + allFruitInView
        
    uniqueObstacles = []
    
    print(f"list is {obstaclesList}")
    
    for obstacles in obstaclesList:
        if all(np.linalg.norm(np.array(obstacles) - np.array(uc)) > THRESHOLD for uc in uniqueObstacles):
            uniqueObstacles.append(obstacles)
    # plot_coordinates_with_radius([robot.state[0][0],robot.state[1][0]], desiredWaypoint ,obstaclesList)
    selectedGoal = desiredWaypoint[0]
    for i in range(0,len(desiredWaypoint)):
        localPath,pos, G = plan_local_path_Astar((robot.state[0][0],robot.state[1][0]),robotAngle=initalAngle,goal=desiredWaypoint[i],obstacles_given=obstaclesList)
    
        if localPath != None:
            selectedGoal = desiredWaypoint[i]
            break
        
    # plotPath = [] 
    # localPath = []
    # try:
    #     if len(localPath) != None:
    #         for j in localPath:
    #             plotPath.append((j[0],j[1]))
        
    # except:
    #     localPath = []
        
    # # local_plot_single_path_and_obstacles(G,pos,plotPath,obstaclesList,(robot.state[0][0],robot.state[1][0]),selectedGoal)
        
    localPath= []    
    plotPath = [] 
    try:
        if localPath != None:
            for j in localPath:
                plotPath.append((j[0],j[1]))
    except:
        localPath = []
        
    # if len(localPath) == 0:
    #     localPath.extend([[0,0]])
        
        
    # local_plot_single_path_and_obstacles(G,pos,plotPath,obstaclesList,(robot.state[0][0],robot.state[1][0]),selectedGoal)
    
    # if len(localPath) == 0:
    #     newRandomX = random.uniform(-0.1, 0.1)
    #     newRandomY = random.uniform(-0.1, 0.1)
    #     print(desiredWaypoint)
    localPath.extend(desiredWaypoint[i:])
    

        
    # print(localPath)
    # input()
    
    # local_plot_single_path_and_obstacles(G,pos,formatPathPlot,obstaclesList,(robot.state[0][0],robot.state[1][0]),selectedGoal)
    
    return localPath
    
def plot_coordinates_with_radius(robotPosition, desiredWaypoint, coordinates, radius=0.08):
    # Create a plot
    fig, ax = plt.subplots(figsize=(10,10))
    square = plt.Rectangle((-1.5, -1.5), 3, 3, fill=False, color='red', label="3x3 Box at Origin")
    plt.gca().add_patch(square)

    # Plot each coordinate as a scatter point
    for coord in coordinates:
        # Plot the scatter point
        ax.scatter(*coord, color='blue')

        # Add a circle around the scatter point with the specified radius
        circle = plt.Circle(coord, radius, color='blue', fill=False, linestyle='--')
        ax.add_patch(circle)

    # Set equal scaling for both axes
    
    robotCircle = plt.Circle(robotPosition, 0.15, color='red', fill=False, linestyle='--')
    ax.add_patch(robotCircle)
    
    goalCircle = plt.Circle(desiredWaypoint, 0.15, color='green', fill=False, linestyle='--')
    ax.add_patch(goalCircle)
    
    ax.set_aspect('equal', adjustable='box')

    # Add grid and labels
    plt.grid(True)
    plt.xlabel('X')
    plt.ylabel('Y')

    # Show the plot
    plt.show()
                
def findClosestObs(listOfAllObs):
    #find the closest obs from the robot, and return a point that can avoid this
    #Input: list of all obs that we will be hitting
    #output: next way point that can avoid hitting the closest obs [x,y]
    
    collisionCoord = None
    minDis = 999
    DIS_FROM_OBS = 0.4 #the distance left/right of the obstals the next way point should be
    
    for i in listOfAllObs:
        prepDis =  math.sqrt((robot.state[0][0] - i[0])**2 + (robot.state[1][0] - i[1]) **2)
        if prepDis < minDis:
            minDis = prepDis
            collisionCoord = [i[0],i[1]]
            
    if collisionCoord != None:
        xNew = DIS_FROM_OBS*np.cos(180-robot[2][0]) + collisionCoord[0]
        yNew = DIS_FROM_OBS*np.sin(180-robot[2][0]) + collisionCoord[0]
        
    return xNew,yNew
  

def startNavV2(trueMap, shoppingList):
    early_plan = False
    allFruitFound  = False
    targetIdx = 0
    while allFruitFound == False:
        currentTarget = shoppingList[targetIdx]
        
        formattedTarget = currentTarget.split('_')[0]
        print("\nTARGET --> "+formattedTarget)

        foundFruit = False
        needNewPath = True
        try:
            goalPoint = (trueMap.get(currentTarget).get('x'),trueMap.get(currentTarget).get('y'))
        except:
            print("\ndo not have current fruit/veg in map\n")
            print("...move to next on list\n\n")
            foundFruit = True
            targetIdx+=1
        
        arriveAtTarget = False
        wayPointIdx = 0
        
        
        while foundFruit == False:
            if needNewPath:
                currentPose = (robot.state[0][0],robot.state[1][0])
                findingPath = True
                lastWayPointIdx = -1
                pathPlannerTimeLimter = 10
                pathPos = 0
                while findingPath:

                    if early_plan == True:
                        early_plan = False
                        # print("\nused early plan")
                    elif early_plan == False:
                        # print("\ndidnt use early plan")
                        newPath,pos, G   = plan_path_Astar(currentPose,goalPoint,trueMap,pathPlannerTimeLimter)
                    print('\n...searched for path\n\n')
                    
                    if newPath == None:                
                        newRandomX = random.uniform(-0.1, 0.1)
                        newRandomY = random.uniform(-0.1, 0.1)
                        currentPose = (0,0)

                        if(pathPlannerTimeLimter)>4:
                            pathPlannerTimeLimter-=0.5
                    else:
                        path = newPath
                        findingPath = False
                        path.pop(0)
                        
                    

                needNewPath = False
                lastWayPoint = True
                wayPointIdx = 0
                # plotCurrentPath(trueMap,G,pos,path,currentPose,goalPoint)
                
            

            nextWayPoint = path[wayPointIdx]
            wayPointIdx += 1
            unobstractedTarget, inCollision,targetLastSeen = driveToPoint(formattedTarget,nextWayPoint,robot.state,goalPoint)
            
            if inCollision:
                if len(path[wayPointIdx :]) == 0:
                    updatedPath = addLocalPath(formattedTarget,[goalPoint])
                
                else:
                    updatedPath = addLocalPath(formattedTarget,path[wayPointIdx :])
                updatedPath.pop(0)
                path = updatedPath
                wayPointIdx = 0
            
            
            elif unobstractedTarget == True:
                ppi.set_velocity([0, 0], tick=30) 
                if len(targetLastSeen)== 0:
                    targetLastSeen = goalPoint
# ----------------------------------------------------------------------------------
                arriveAtTarget = driveToTarget(formattedTarget, targetLastSeen)

                if arriveAtTarget == True:
                    print("======ARRIVED AT TARGET========")
                    foundFruit = True
                    targetIdx+=1

                    start_time = time.time()
                    # -------- if last fruit is found ------------ 
                    if currentTarget == shoppingList[-1]: 
                        print("\n\n\n\n\n last fruit found!!!!\n\n")
                        allFruitFound = True
                        celebrate()
                        break
                    # -------- run next astar------------ (repeat of above code)
                    else:
                        currentTarget = shoppingList[targetIdx]
                        try:
                            goalPoint = (trueMap.get(currentTarget).get('x'),trueMap.get(currentTarget).get('y'))
                        except:
                            print("\ndo not have current fruit/veg in map\n")
                            print("...move to next on list\n\n")
                            foundFruit = True
                            targetIdx+=1
                        # goalPoint = (trueMap.get(currentTarget).get('x'),trueMap.get(currentTarget).get('y'))
                        newPath,pos, G   = plan_path_Astar(currentPose,goalPoint,trueMap,pathPlannerTimeLimter)
                        early_plan = True
                    # -------------------- (repeat of above code)
                    
                    print(f"\n\n======collecting {formattedTarget} (2secs)")
                    while time.time() - start_time < 2:
                        print(f"\n\n======collecting {formattedTarget} (2secs)")
                        time.sleep(0.2)
                    print("\n\n-----next on the list \n\n")
                    break

                else:
                    needNewPath = True
                    unobstractedTarget = False
                    break
# ----------------------------------------------------------------------------------
                
                
            if wayPointIdx == len(path):
                if targetLastSeen == None:
                    targetLastSeen = goalPoint
# ----------------------------------------------------------------------------------
                arriveAtTarget = driveToTarget(formattedTarget, targetLastSeen)

                if arriveAtTarget == True:
                    print("======ARRIVED AT TARGET========")
                    foundFruit = True
                    targetIdx+=1

                    start_time = time.time()
                    # -------- if last fruit is found ------------ 
                    if currentTarget == shoppingList[-1]: 
                        print("\n\n\n\n\n last fruit found!!!!\n\n")
                        allFruitFound = True
                        celebrate()
                        break
                    # -------- run next astar------------ (repeat of above code)
                    else:
                        currentTarget = shoppingList[targetIdx]
                        goalPoint = (trueMap.get(currentTarget).get('x'),trueMap.get(currentTarget).get('y'))
                        newPath,pos, G   = plan_path_Astar(currentPose,goalPoint,trueMap,pathPlannerTimeLimter)
                        early_plan = True
                    # -------------------- (repeat of above code)
                    
                    print(f"\n\n======collecting {formattedTarget} (2secs)")
                    while time.time() - start_time < 2:
                        print(f"\n\n======collecting {formattedTarget} (2secs)")
                        time.sleep(0.2)
                    print("\n\n-----next on the list \n\n")
                    break
                else:
                    needNewPath = True
                    unobstractedTarget = False
                    break
# ----------------------------------------------------------------------------------

            ppi.set_velocity([0, 0], tick=30)

if __name__ == "__main__":
    
    parser = argparse.ArgumentParser("Fruit searching")
    parser.add_argument("--map", type=str, default='est_maps/estMap1.txt') # change to 'M4_true_map_part.txt' for lv2&3
    parser.add_argument("--ip", metavar='', type=str, default='192.168.50.1')
    parser.add_argument("--port", metavar='', type=int, default=8080)
    
    parser.add_argument("--filter", type=str, default='1,2,3,4,5', help="index seperated by (,)")
    args, _ = parser.parse_known_args()
    
    
    fileS = "calibration/param/scale.txt"
    scale = np.loadtxt(fileS, delimiter=',')
    fileB = "calibration/param/baseline.txt"
    baseline = np.loadtxt(fileB, delimiter=',')
    fileC = "calibration/param/intrinsic.txt"
    camera_matrix = np.loadtxt(fileC, delimiter=',')
    fileD = "calibration/param/distCoeffs.txt"
    dist_coeffs = np.loadtxt(fileD, delimiter=',')
    
    script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)
    
    model_path = f'{script_dir}/YOLO/model/best.pt'
    yolo = Detector(model_path)

    ppi = PenguinPi(args.ip,args.port)
    ppi.set_velocity([0, 0], tick= 30)
    robot = Robot(baseline,scale,camera_matrix,dist_coeffs)
    ekf = EKF(robot)
    control_clock = time.time()
    aruco_det = aruco.aruco_detector(robot,marker_length=0.07) #initalise the aruco detector

    trueMap = read_true_map(args.map)
    search_list = read_search_list()

    print(f"=========== search list=======\n\t{search_list}")
    for i in range(len(search_list)):
        print(search_list[i])
        search_list[i] = search_list[i]+"_0"
        target_pose_dict = {}
        detected_type_list = []
        
    # --------------------- if you want to remove an item from shopping list--------------------------------
    # filter = input("Do you want to filter shopping list? [y/n] \n")
    
    if args.filter:
        # Convert the defined index string to a list of integers (convert to 0-based indexing)
        indices = [int(i)-1 for i in args.filter.split(',')]
        # Filter the list based on the indices
        filtered_list = [search_list[i] for i in indices]
        print(filtered_list)
        search_list = filtered_list
    # ------------------------------------------------------------------------------------------------------
    
    autoNav = input("AUTO NAV [y/n] ")
    
    if autoNav:
        startNavV2(trueMap, search_list)

# python3 auto_fruit_search_final_V2 --filter 1,2,3,4,5




