# import numpy as np
# import json
# import os
# import ast
# import cv2
# from YOLO.detector import Detector
# from sklearn.cluster import KMeans
# from scipy.cluster.hierarchy import linkage, fcluster
# from copy import deepcopy



# # list of target fruits and vegs types
# # Make sure the names are the same as the ones used in your YOLO model
# TARGET_TYPES = ['pear', 'lemon', 'lime', 'tomato', 'capsicum', 'potato', 'pumpkin', 'garlic']


# def estimate_pose(camera_matrix, obj_info, robot_pose):
#     """
#     function:
#         estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
#     input:
#         camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
#             |f_x, s,   c_x|
#             |0,   f_y, c_y|
#             |0,   0,   1  |
#             (f_x, f_y): focal length in pixels
#             (c_x, c_y): optical centre in pixels
#             s: skew coefficient (should be 0 for PenguinPi)
#         obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
#         robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
#     output:
#         target_pose: dict, prediction of target pose
#     """
#     # read in camera matrix (from camera calibration results)
#     focal_length = camera_matrix[0][0]

#     # there are 8 possible types of fruits and vegs
#     ######### Replace with your codes #########
#     # TODO: measure actual sizes of targets [width, depth, height] and update the dictionary of true target dimensions
#     # target_dimensions_dict = {'pear': [156,151,0.101], 'lemon': [1.0,1.0,0.0522], 
#     #                           'lime': [1.0,1.0,0.04925], 'tomato': [1.0,1.0,0.072],#tomato good garlic good, pumpkin good
#     #                           'capsicum': [1.0,1.0,0.0883], 'potato': [1.0,1.0,0.0643], 
#     #                           'pumpkin': [1.0,1.0,0.0670], 'garlic': [1.0,1.0,0.0793]}
#     target_dimensions_dict = {'pear': [156,151,0.0914], 'lemon': [1.0,1.0,0.0517], 
#                               'lime': [1.0,1.0,0.053], 'tomato': [1.0,1.0,0.068],#tomato good garlic good, pumpkin good
#                               'capsicum': [1.0,1.0,0.0963], 'potato': [1.0,1.0,0.0563], 
#                               'pumpkin': [1.0,1.0,0.074], 'garlic': [1.0,1.0,0.0783],'orange': [1, 1, 79]}
#     #########

#     # estimate target pose using bounding box and robot pose
#     target_class = obj_info[0]     # get predicted target label of the box
#     target_box = obj_info[1]       # get bounding box measures: [x,y,width,height]
#     true_height = target_dimensions_dict[target_class][2]   # look up true height of by class label

#     # compute pose of the target based on bounding box info, true object height, and robot's pose
#     pixel_height = target_box[3]
#     pixel_center = target_box[0]
#     distance = true_height/pixel_height * focal_length  # estimated distance between the robot and the centre of the image plane based on height
#     # training image size 320x240p
#     image_width = 320 # change this if your training image is in a different size (check details of pred_0.png taken by your robot)
#     x_shift = image_width/2 - pixel_center              # x distance between bounding box centre and centreline in camera view
#     theta = np.arctan(x_shift/focal_length)     # angle of object relative to the robot
#     ang = theta + robot_pose[2]     # angle of object in the world frame
    
#    # relative object location
#     distance_obj = distance/np.cos(theta) # relative distance between robot and object
#     x_relative = distance_obj * np.cos(theta) # relative x pose
#     y_relative = distance_obj * np.sin(theta) # relative y pose
#     relative_pose = {'x': x_relative, 'y': y_relative}
#     #print(f'relative_pose: {relative_pose}')

#     # location of object in the world frame using rotation matrix
#     delta_x_world = x_relative * np.cos(robot_pose[2]) - y_relative * np.sin(robot_pose[2])
#     delta_y_world = x_relative * np.sin(robot_pose[2]) + y_relative * np.cos(robot_pose[2])
#     # add robot pose with delta target pose
#     target_pose = {'y': (robot_pose[1]+delta_y_world)[0],
#                    'x': (robot_pose[0]+delta_x_world)[0]}
#     #print(f'delta_x_world: {delta_x_world}, delta_y_world: {delta_y_world}')
#     #print(f'target_pose: {target_pose}')

#     return target_pose
# # def merge_estimations(target_pose_dict):
    
# #     """
# #     function:
# #         merge estimations of the same target
# #     input:math.dist
# #         target_pose_dict: dict, generated by estimate_pose
# #     output:
# #         target_est: dict, target pose estimations after merging
# #     """
# #     # x_values=[]
# #     # y_values=[]
# #     target_est = {}
# #     sorted_target_data ={}
# #     amount={}
# #     ######### Replace with your codes #########
# #     # TODO: replace it with a solution to merge the multiple occurrences of the same class type (e.g., by a distance threshold)
# #     # print(target_pose_dict)
# #     for key, value in target_pose_dict.items():
# #     # Split the key by the underscore to separate detection type and occurrence
# #         detection, occurrence = key.rsplit('_', 1)
# #         # print(detection)
# #         if detection not in sorted_target_data:
# #             sorted_target_data[detection] = []
# #     # Add the detection to the corresponding list in individual_detections
# #         sorted_target_data[detection]=np.append(sorted_target_data[detection],value)
# #         amount[detection]=len(sorted_target_data[detection])
        
# #     #print(sorted_target_data)
# #     # print(sorted_target_data[detection])
    
# #     for detection in sorted_target_data:
# #         if amount[detection]<2:
            
# #             target_est[detection+'_'+str(0)]=sorted_target_data[detection][0]
# #             # print("garlic")
# #         else:
# #             numeric_data = [[d['y'], d['x']] for d in sorted_target_data[detection]]
# #             #print((numeric_data[0]))
            
# #             groups = linkage(numeric_data, 'single', 'euclidean')
            
# #             clusters = fcluster(groups, 0.3, criterion='distance')
# #             # n = 2 if len(sorted_target_data[detection]) > 1 else len(sorted_target_data[detection])
# #             # clustered = KMeans(init="k-means++",n_clusters=n,random_state=0)
# #             #estimated = clustered.fit_predict(numeric_data)
# #             #print(clusters)
# #             # print((numeric_data))
# #             x_values=[]
# #             y_values=[]
# #             # for cls in np.unique(clusters):
# #             #     # if cls>1:
# #             #     #     target_index=np.where(clusters==cls)
# #             #     #     sorted_target_data[detection] = np.delete(sorted_target_data[detection], target_index, axis=0)
# #             #     # else:
# #             print(detection)
# #             #en(set(clusters))
# #             coords_cls=[]
# #             for j in range(len(clusters)):
                
# #                 coords_cls.append(sorted_target_data[detection][j])

# #                 # print(coords_cls[0])   
# #             #print(len(coords_cls))
# #             for i in range(len(coords_cls)):

# #                 # print(sorted_target_data[detection][i])

                

# #                 #print(i)

# #                 if coords_cls[i]['x']>1.5:
# #                     # old=coords_cls[i]['x']

# #                     # dist_change=coords_cls[i]['x']-1.4

# #                     coords_cls[i]['x']=1.45

# #                     # coords_cls[i]['y']=coords_cls[i]['y']-dist_change*coords_cls[i]['y']/old

# #                 elif coords_cls[i]['x']<-1.5:

# #                     # old=coords_cls[i]['x']

# #                     # dist_change=coords_cls[i]['x']+1.4

# #                     coords_cls[i]['x']=-1.45

# #                     # coords_cls[i]['y']=coords_cls[i]['y']-dist_change*coords_cls[i]['y']/old

# #                 if coords_cls[i]['y']>1.5:

# #                     # old=coords_cls[i]['y']

# #                     # dist_change=coords_cls[i]['y']-1.4

# #                     # coords_cls[i]['x']=coords_cls[i]['x']-dist_change*coords_cls[i]['x']/old

# #                     coords_cls[i]['y']=1.45

# #                 elif coords_cls[i]['y'] < -1.5:

# #                     # old=coords_cls[i]['y']

# #                     # dist_change=coords_cls[i]['y']+1.4

# #                     # coords_cls[i]['x']=coords_cls[i]['x']-dist_change*coords_cls[i]['x']/old

# #                     coords_cls[i]['y']=-1.45
# #                 print(detection)
# #                 print(y_values)
# #                 x_values.append(coords_cls[i]["x"])
# #                 y_values.append(coords_cls[i]["y"])
# #         #print(x_values)    
# #         # print(sorted_target_data)
# #             if len(set(clusters))>1:
# #                 n=2
# #             else:
# #                 n=1
# #             X = np.array(list(zip(x_values, y_values)))
# #             kmeans = KMeans(init="k-means++",n_clusters=n).fit(X)
# #             centroids=kmeans.cluster_centers_.ravel()
# #             kmeans_labels = KMeans(init="k-means++",n_clusters=n)
# #             print(centroids)
# #             print(kmeans_labels)
# #             # x_med=np.mean(x_values)
# #             # # print(detection)
# #             # # print(x_values)
# #             # #print(x_values)
# #             # y_med=np.mean(y_values)
# #             # print(len(centroids))
# #             for i in range(int(len(centroids)/2)):
# #                 target_est[detection+'_'+str(i)] = {"y": centroids[i+1], "x":centroids[i]}
                
# #                 # clsName = f"detection_{cls-1}"
# #                 # target_est[clsName] = {"x": x_med, "y":y_med}

# #             #print( x_values)
# #     #########
   
# #     return target_est


# def merge_estimations(target_pose_dict):

    

#     """

#     function:

#         merge estimations of the same target

#     input:math.dist

#         target_pose_dict: dict, generated by estimate_pose

#     output:

#         target_est: dict, target pose estimations after merging

#     """

#     # x_values=[]

#     # y_values=[]

#     target_est = {}

#     sorted_target_data ={}

#     amount={}

#     ######### Replace with your codes #########

#     # TODO: replace it with a solution to merge the multiple occurrences of the same class type (e.g., by a distance threshold)

#     # print(target_pose_dict)

#     for key, value in target_pose_dict.items():

#     # Split the key by the underscore to separate detection type and occurrence

#         detection, occurrence = key.rsplit('_', 1)

#         # print(detection)

#         if detection not in sorted_target_data:

#             sorted_target_data[detection] = []

#     # Add the detection to the corresponding list in individual_detections

#         sorted_target_data[detection]=np.append(sorted_target_data[detection],value)

#         amount[detection]=len(sorted_target_data[detection])

        

#     #print(sorted_target_data)

#     # print(sorted_target_data[detection])

    

#     for detection in sorted_target_data:
#         if amount[detection]<2:
            
#             target_est[detection+'_'+str(0)]=sorted_target_data[detection][0]
#             # print("garlic")
#         else:
    

#             numeric_data = [[d['y'], d['x']] for d in sorted_target_data[detection]]

#             #print((numeric_data[0]))

            

#             groups = linkage(numeric_data, 'single', 'euclidean')

            

#             clusters = fcluster(groups, 0.7, criterion='distance')

#             # n = 2 if len(sorted_target_data[detection]) > 1 else len(sorted_target_data[detection])

#             # clustered = KMeans(init="k-means++",n_clusters=n,random_state=0)

#             #estimated = clustered.fit_predict(numeric_data)

#             #print(clusters)

#             # print((numeric_data))

#             x_values=[]

#             y_values=[]

#             # for cls in np.unique(clusters):

#             #     # if cls>1:

#             #     #     target_index=np.where(clusters==cls)

#             #     #     sorted_target_data[detection] = np.delete(sorted_target_data[detection], target_index, axis=0)

#             #     # else:

#             print(detection)

#             #en(set(clusters))

#             coords_cls=[]

#             for j in range(len(clusters)):

                

#                 coords_cls.append(sorted_target_data[detection][j])




#                 # print(coords_cls[0])   

#             #print(len(coords_cls))

#             for i in range(len(coords_cls)):




#                 # print(sorted_target_data[detection][i])




                




#                 #print(i)




#                 if coords_cls[i]['x']>1.5:

#                     old=coords_cls[i]['x']




#                     dist_change=coords_cls[i]['x']-1.4




#                     coords_cls[i]['x']=1.4




#                     coords_cls[i]['y']=coords_cls[i]['y']-dist_change*coords_cls[i]['y']/abs(old)




#                 elif coords_cls[i]['x']<-1.5:




#                     old=coords_cls[i]['x']




#                     dist_change=coords_cls[i]['x']+1.4




#                     coords_cls[i]['x']=-1.4




#                     coords_cls[i]['y']=coords_cls[i]['y']-dist_change*coords_cls[i]['y']/old




#                 if coords_cls[i]['y']>1.5:




#                     old=coords_cls[i]['y']




#                     dist_change=coords_cls[i]['y']-1.4




#                     coords_cls[i]['x']=coords_cls[i]['x']-dist_change*coords_cls[i]['x']/old




#                     coords_cls[i]['y']=1.4




#                 elif coords_cls[i]['y']<-1.5:




#                     old=coords_cls[i]['y']




#                     dist_change=coords_cls[i]['y']+1.4




#                     coords_cls[i]['x']=coords_cls[i]['x']-dist_change*coords_cls[i]['x']/old




#                     coords_cls[i]['y']=-1.4

#                 x_values.append(coords_cls[i]["x"])

#                 y_values.append(coords_cls[i]["y"])

#             #print(x_values)    

#             # print(sorted_target_data)

#             if len(set(clusters))>1:

#                 n=2

#             else:

#                 n=1

#             X = np.array(list(zip(x_values, y_values)))

#             kmeans = KMeans(init="k-means++",n_clusters=n).fit(X)

#             centroids=kmeans.cluster_centers_.ravel()

#             print(centroids)

#             clustered = KMeans(init="k-means++",n_clusters=n,random_state=0)

#             estimated = clustered.fit_predict(numeric_data)




#             print(estimated)

#             x_val=[]

#             y_val=[]

#             for cls in np.unique(estimated):

                

#                 target_index=np.where(estimated==cls)

#                 print(target_index[0][1])

#                 for i in range(len(target_index)):

#                     x_val.append(coords_cls[target_index[0][i]]["x"])

#                     y_val.append(coords_cls[target_index[0][i]]["y"])

#                 x_med=np.median(x_val)

#                 y_med=np.median(y_val)

#                 target_est[detection+'_'+str(cls)] = {"x": x_med, "y":y_med}

#         # x_med=np.mean(x_values)

#         # print(x_med)

#         # print(y_med)

#         # # # print(x_values)

#         # # #print(x_values)

#         # # y_med=np.mean(y_values)

#         # print(len(centroids))

#         # for i in range(int(len(centroids)/2)):

#         #     target_est[detection+'_'+str(i)] = {"x": centroids[i], "y":centroids[i+1]}

            

#         #     # clsName = f"detection_{cls-1}"

#         #     # target_est[clsName] = {"x": x_med, "y":y_med}




#         #print( x_values)

#     #########

   

#     return target_est

# def parse_slam_map(fname: str) -> dict:
#     with open(fname, 'r') as fd:
#         usr_dict = json.load(fd)
#     aruco_dict = {}
#     for (i, tag) in enumerate(usr_dict["taglist"]):
#         aruco_dict[tag] = np.reshape([usr_dict["map"][0][i], usr_dict["map"][1][i]], (2, 1))
    
#     # print(f'Estimated marker poses: {aruco_dict}')
#     sortedDict = dict(sorted(aruco_dict.items()))
    
#     item_10 = {10: sortedDict.pop(10)}
#     sortedDict = {**item_10, **sortedDict}
#     # print(f"sorted DIC is \n{sortedDict}")
    
#     formattedMap = {}
    
#     for i in sortedDict:
#         print(i)
#         print(sortedDict.get(i))
#         xVal = sortedDict.get(i)[0][0]
#         yVal = sortedDict.get(i)[1][0]
#         # "aruco"+str(i)
#         formattedName = f"aruco{i}_0" 
#         if i <= 10:
#             formattedMap[formattedName] = {"x":xVal,"y":yVal}
    
#     print(f"formatted map is \n{formattedMap}")
    
#     return formattedMap

# # read estimated target map 'lab_output/targets.txt'
# def parse_object_map(fname):
#     with open(fname, 'r') as fd:
#         usr_dict = json.load(fd)
#     target_dict = {}

#     for key in usr_dict:
#         object_type = key.split('_')[0]
#         if object_type not in target_dict:
#             target_dict[object_type] = np.array([[usr_dict[key]["x"], usr_dict[key]["y"]]])
#         else:
#             target_dict[object_type] = np.append(target_dict[object_type], [[usr_dict[key]["x"], usr_dict[key]["y"]]], axis=0)

#     # print(f'Estimated target poses: {target_dict}')
#     formattedObject = {}
    
#     for fruit in target_dict:
#         # print(fruit)
#         # print(target_dict.get(fruit))
#         objectPos = target_dict.get(fruit)
        
#         for i in range(0,len(objectPos)):
#             xVal = objectPos[i][0]
#             yVal = objectPos[i][1]
            
#             formattedName = f"{fruit}_{i}"
            
#             formattedObject[formattedName] = {"x":xVal,"y":yVal}
            
#             # print(f"{fruit}_{i}")
#             # print(objectPos[i])
            
#     # print("format list below \n\n\n")
            
#     # print(formattedObject)
                    
#     return formattedObject


# # main loop
# if __name__ == "__main__":
#     import argparse
#     #input target.txt, slam.txt
#     #output est position of all object in GT map format
    
#     parser = argparse.ArgumentParser('Matching the estimated map and the true map')
#     parser.add_argument('--slam-est', type=str, default='lab_output/slam.txt') # slam file from the sun


#     script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)

#     # read in camera matrix
#     fileK = f'{script_dir}/calibration/param/intrinsic.txt'
#     camera_matrix = np.loadtxt(fileK, delimiter=',')

#     # init YOLO model
#     model_path = f'{script_dir}/YOLO/model/best.pt'
#     yolo = Detector(model_path)

#     # create a dictionary of all the saved images with their corresponding robot pose
#     image_poses = {}
#     with open(f'{script_dir}/lab_output/images.txt') as fp:
#         for line in fp.readlines():
#             pose_dict = ast.literal_eval(line)
#             image_poses[pose_dict['imgfname']] = pose_dict['pose']
#     #print(image_poses)
#     # estimate pose of targets in each image
#     target_pose_dict = {}
#     detected_type_list = []
#     for image_path in image_poses.keys():
#         # image_path2="/home/cailan/catkin_ws/ECE4078_Lab_2024/Week02-04/"+image_path
#         # image_path2=image_path2.replace('png', 'PNG')
#         #print(os.path.exists(image_path2))
#         input_image = cv2.imread(image_path)
#         #print(input_image)
#         bounding_boxes, bbox_img = yolo.detect_single_image(input_image)
#         # cv2.imshow('bbox', bbox_img)
#         # cv2.waitKey(0)
#         robot_pose = image_poses[image_path]

#         for detection in bounding_boxes:
#             # count the occurrence of each target type
#             occurrence = detected_type_list.count(detection[0])
#             target_pose_dict[f'{detection[0]}_{occurrence}'] = estimate_pose(camera_matrix, detection, robot_pose)
            
#             detected_type_list.append(detection[0])

#     # merge the estimations of the targets so that there are at most 3 estimations of each target type
#     target_est = {}
#     target_est = merge_estimations(target_pose_dict)
#     # print(target_est)
#     # save target pose estimations
#     with open(f'{script_dir}/lab_output/targetsUPSTAR.txt', 'w') as fo:
#         json.dump(target_est, fo, indent=4)
        
        
#     args, _ = parser.parse_known_args()
    
#     aruco_est = parse_slam_map(args.slam_est)
    
#     aruco_est.update(target_est)
    

#     #making a "true" map for auto nav

#     print('Estimations saved!')
    
#     print(aruco_est)
    
#     with open(f'{script_dir}/est_maps/estMap1.txt', 'w') as fo:
#         json.dump(aruco_est, fo, indent=4)




# estimate the pose of target objects detected and generate a truemap like file
import numpy as np
import json
import os
import ast
import cv2
from YOLO.detector import Detector
from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import linkage, fcluster
from copy import deepcopy



# list of target fruits and vegs types
# Make sure the names are the same as the ones used in your YOLO model
TARGET_TYPES = ['pear', 'lemon', 'lime', 'tomato', 'capsicum', 'potato', 'pumpkin', 'garlic']

def estimate_pose(camera_matrix, obj_info, robot_pose):
    """
    function:
        estimate the pose of a target based on size and location of its bounding box and the corresponding robot pose
    input:
        camera_matrix: list, the intrinsic matrix computed from camera calibration (read from 'param/intrinsic.txt')
            |f_x, s,   c_x|
            |0,   f_y, c_y|
            |0,   0,   1  |
            (f_x, f_y): focal length in pixels
            (c_x, c_y): optical centre in pixels
            s: skew coefficient (should be 0 for PenguinPi)
        obj_info: list, an individual bounding box in an image (generated by get_bounding_box, [label,[x,y,width,height]])
        robot_pose: list, pose of robot corresponding to the image (read from 'lab_output/images.txt', [x,y,theta])
    output:
        target_pose: dict, prediction of target pose
    """
    # read in camera matrix (from camera calibration results)
    focal_length = camera_matrix[0][0]

    # there are 8 possible types of fruits and vegs
    ######### Replace with your codes #########
    # TODO: measure actual sizes of targets [width, depth, height] and update the dictionary of true target dimensions
    
    target_dimensions_dict = {'pear': [0.080,151,0.089], 'lemon': [1.0,1.0,0.054], 
                              'lime': [1.0,1.0,0.054], 'tomato': [0.0691,1.0,0.074],#tomato good garlic good, pumpkin good
                              'capsicum': [0.076,1.0,0.088], 'potato': [1.0,1.0,0.067], 
                              'pumpkin': [0.083,1.0,0.082], 'garlic': [0.065,1.0,0.0783],'orange': [1, 1, 79]}    

    # target_dimensions_dict = {'pear': [0.081,151,0.0954], 'lemon': [1.0,1.0,0.0507], 
    #                           'lime': [1.0,1.0,0.0500], 'tomato': [0.0690,1.0,0.068],#tomato good garlic good, pumpkin good
    #                           'capsicum': [0.086,1.0,0.0933], 'potato': [1.0,1.0,0.0583], 
    #                           'pumpkin': [0.085,1.0,0.073], 'garlic': [0.065,1.0,0.0783],'orange': [1, 1, 79]}
    # ########
    # target_dimensions_dict = {'pear': [0.081,151,0.101135], 'lemon': [1.0,1.0,0.0474652], 
    #                           'lime': [1.0,1.0,0.0500], 'tomato': [0.0739861,1.0,0.068],#tomato good garlic good, pumpkin good
    #                           'capsicum': [0.0960603,1.0,0.0933], 'potato': [1.0,1.0,00.0521828], 
    #                           'pumpkin': [0.085,1.0,0.073], 'garlic': [0.065,1.0,0.0783],'orange': [1, 1, 79]}
    # estimate target pose using bounding box and robot pose
    target_class = obj_info[0]     # get predicted target label of the box
    target_box = obj_info[1]       # get bounding box measures: [x,y,width,height]
    true_height = target_dimensions_dict[target_class][2]   # look up true height of by class label
    true_width = target_dimensions_dict[target_class][0]   # look up true height of by class label
    true_depth = target_dimensions_dict[target_class][1]

    # compute pose of the target based on bounding box info, true object height, and robot's pose
    pixel_height = target_box[3]
    pixel_width = target_box[2]
    pixel_center = target_box[0]
    w_distance = true_width/pixel_width * focal_length
    h_distance = true_height/pixel_height * focal_length  # estimated distance between the robot and the centre of the image plane based on height
    # training image size 320x240p
    image_width = 320 # change this if your training image is in a different size (check details of pred_0.png taken by your robot)
    x_shift = image_width/2 - pixel_center              # x distance between bounding box centre and centreline in camera view
    theta = np.arctan(x_shift/focal_length)     # angle of object relative to the robot
    ang = theta + robot_pose[2]     # angle of object in the world frame
    
#    # relative object location
    if target_class in [ 'pumpkin', 'capsicum', 'garlic', 'tomato']:
        distance_obj = w_distance/np.cos(theta)
        
    else:
        distance_obj = h_distance/np.cos(theta)   # relative distance between robot and object
    x_relative = distance_obj * np.cos(theta) # relative x pose
    y_relative = distance_obj * np.sin(theta) # relative y pose
    relative_pose = {'x': x_relative, 'y': y_relative}
    #print(f'relative_pose: {relative_pose}')

    # location of object in the world frame using rotation matrix
    delta_x_world = x_relative * np.cos(robot_pose[2]) - y_relative * np.sin(robot_pose[2])
    delta_y_world = x_relative * np.sin(robot_pose[2]) + y_relative * np.cos(robot_pose[2])
    # add robot pose with delta target pose
    target_pose = {'y': (robot_pose[1]+delta_y_world)[0],
                   'x': (robot_pose[0]+delta_x_world)[0]}
    #print(f'delta_x_world: {delta_x_world}, delta_y_world: {delta_y_world}')
    #print(f'target_pose: {target_pose}')

    return target_pose
def merge_estimations(target_pose_dict):
    
    """
    function:
        merge estimations of the same target
    input:math.dist
        target_pose_dict: dict, generated by estimate_pose
    output:
        target_est: dict, target pose estimations after merging
    """
    # x_values=[]
    # y_values=[]
    target_est = {}
    sorted_target_data ={}
    amount={}
    ######### Replace with your codes #########
    # TODO: replace it with a solution to merge the multiple occurrences of the same class type (e.g., by a distance threshold)
    # print(target_pose_dict)
    for key, value in target_pose_dict.items():
    # Split the key by the underscore to separate detection type and occurrence
        detection, occurrence = key.rsplit('_', 1)
        # print(detection)
        if detection not in sorted_target_data:
            sorted_target_data[detection] = []
    # Add the detection to the corresponding list in individual_detections
        sorted_target_data[detection]=np.append(sorted_target_data[detection],value)
        amount[detection]=len(sorted_target_data[detection])
        
    #print(sorted_target_data)
    # print(sorted_target_data[detection])
    
    for detection in sorted_target_data:
        if amount[detection]<2:
            
            target_est[detection+'_'+str(0)]=sorted_target_data[detection][0]
        else:
            numeric_data = [[d['y'], d['x']] for d in sorted_target_data[detection]]
            #print((numeric_data[0]))
            
            groups = linkage(numeric_data, 'single', 'euclidean')
            
            clusters = fcluster(groups, 0.5, criterion='distance')
            # n = 2 if len(sorted_target_data[detection]) > 1 else len(sorted_target_data[detection])
            # clustered = KMeans(init="k-means++",n_clusters=n,random_state=0)
            #estimated = clustered.fit_predict(numeric_data)
            #print(clusters)
            # print((numeric_data))
            x_values=[]
            y_values=[]
            # for cls in np.unique(clusters):
            #     # if cls>1:
            #     #     target_index=np.where(clusters==cls)
            #     #     sorted_target_data[detection] = np.delete(sorted_target_data[detection], target_index, axis=0)
            #     # else:
            # print(detection)
            #en(set(clusters))
            coords_cls=[]
            for j in range(len(clusters)):
                
                coords_cls.append(sorted_target_data[detection][j])

                # print(coords_cls[0])   
            #print(len(coords_cls))
            for i in range(len(coords_cls)):
                print(f"hereee running {coords_cls[i]['x']},{coords_cls[i]['y']}")

                # print(sorted_target_data[detection][i])
                # #print(i)

                if coords_cls[i]['x']>1.5:
                    # old=coords_cls[i]['x']

                    # dist_change=coords_cls[i]['x']-1.4

                    coords_cls[i]['x']=1.45

                    # coords_cls[i]['y']=coords_cls[i]['y']-dist_change*coords_cls[i]['y']/abs(old)

                elif coords_cls[i]['x']<-1.5:

                    # old=coords_cls[i]['x']

                    # dist_change=coords_cls[i]['x']+1.4
                    print(f"before change is {coords_cls[i]['x']}")
                    

                    coords_cls[i]['x']=-1.45
                    print(f"after change is {coords_cls[i]['x']}")
                    
                    

                    # coords_cls[i]['y']=coords_cls[i]['y']-dist_change*coords_cls[i]['y']/old

                if coords_cls[i]['y']>1.5:

                    # old=coords_cls[i]['y']

                    # dist_change=coords_cls[i]['y']-1.4

                    # coords_cls[i]['x']=coords_cls[i]['x']-dist_change*coords_cls[i]['x']/old

                    coords_cls[i]['y']=1.45

                elif coords_cls[i]['y']< -1.5:

                    # old=coords_cls[i]['y']

                    # dist_change=coords_cls[i]['y']+1.4

                    # coords_cls[i]['x']=coords_cls[i]['x']-dist_change*coords_cls[i]['x']/old

                    coords_cls[i]['y']= -1.5
                x_values.append(coords_cls[i]["x"])
                y_values.append(coords_cls[i]["y"])
            #print(x_values)    
            # print(sorted_target_data)
            
            if len(set(clusters))>1:
                n=2
            else:
                n=1
            X = np.array(list(zip(x_values, y_values)))
            kmeans = KMeans(init="k-means++",n_clusters=n).fit(X)
            centroids=kmeans.cluster_centers_.ravel()
            # print(centroids)
            clustered = KMeans(init="k-means++",n_clusters=n,random_state=0)
            estimated = clustered.fit_predict(X)

            print(centroids)
            
            
            for cls in np.unique(estimated):
                # print(cls)
                x_val=[]
                y_val=[]
                target_index=np.where(estimated==cls)
                distance=[]
                # print(len(target_index[0]))
                for i in range(len(target_index[0])):
                    distance.append(np.sqrt((coords_cls[target_index[0][i]]["x"]-centroids[2*cls])**2+(coords_cls[target_index[0][i]]["y"]-centroids[2*cls+1])**2))
                    # print(coords_cls[target_index[0][i]])
                    # print(detection)
                    # print(coords_cls[target_index[0][i]]["y"])
                    # print(centroids[cls])

                
                
                res = sorted(range(len(distance)),key=lambda sub: distance[sub])[:2]
                # print(res)   
                # print(coords_cls)
                for k in res:
                    x_val.append(coords_cls[target_index[0][k]]["x"])
                    y_val.append(coords_cls[target_index[0][k]]["y"])
                # print(distance)
                # print(y_val)

                # print(centroids)
                # target_est[detection+'_'+str(cls)] = {"x": (sum(x_val)+centroids[2*cls])/3, "y":(sum(y_val)+centroids[2*cls+1])/3}
                
                
                # target_est[detection+'_'+str(cls)] = {"x": centroids[cls], "y":centroids[cls+1]}

                
            
            #     x_med=np.median(x_val)
            #     y_med=np.median(y_val)
            #     target_est[detection+'_'+str(cls)] = {"x": x_med, "y":y_med}
            # x_med=np.mean(x_values)
            # print(x_med)
            # print(y_med)
            # # # print(x_values)
            # # #print(x_values)
            # # y_med=np.mean(y_values)
            # print(len(centroids))
            
            for i in range(int(len(centroids)/2)):
                
                target_est[detection+'_'+str(i)] = {"x": centroids[2*i], "y":centroids[2*i+1]}
            
        #     # clsName = f"detection_{cls-1}"
        #     # target_est[clsName] = {"x": x_med, "y":y_med}

        #print( x_values)
    #########
   
    return target_est



def parse_slam_map(fname: str) -> dict:
    with open(fname, 'r') as fd:
        usr_dict = json.load(fd)
    aruco_dict = {}
    for (i, tag) in enumerate(usr_dict["taglist"]):
        aruco_dict[tag] = np.reshape([usr_dict["map"][0][i], usr_dict["map"][1][i]], (2, 1))
    
    # print(f'Estimated marker poses: {aruco_dict}')
    sortedDict = dict(sorted(aruco_dict.items()))
    
    item_10 = {10: sortedDict.pop(10)}
    sortedDict = {**item_10, **sortedDict}
    # print(f"sorted DIC is \n{sortedDict}")
    
    formattedMap = {}
    
    for i in sortedDict:
        print(i)
        print(sortedDict.get(i))
        xVal = sortedDict.get(i)[0][0]
        yVal = sortedDict.get(i)[1][0]
        # "aruco"+str(i)
        formattedName = f"aruco{i}_0" 
        if i <= 10:
            formattedMap[formattedName] = {"x":xVal,"y":yVal}
    
    print(f"formatted map is \n{formattedMap}")
    
    return formattedMap

# read estimated target map 'lab_output/targets.txt'
def parse_object_map(fname):
    with open(fname, 'r') as fd:
        usr_dict = json.load(fd)
    target_dict = {}

    for key in usr_dict:
        object_type = key.split('_')[0]
        if object_type not in target_dict:
            target_dict[object_type] = np.array([[usr_dict[key]["x"], usr_dict[key]["y"]]])
        else:
            target_dict[object_type] = np.append(target_dict[object_type], [[usr_dict[key]["x"], usr_dict[key]["y"]]], axis=0)

    # print(f'Estimated target poses: {target_dict}')
    formattedObject = {}
    
    for fruit in target_dict:
        # print(fruit)
        # print(target_dict.get(fruit))
        objectPos = target_dict.get(fruit)
        
        for i in range(0,len(objectPos)):
            xVal = objectPos[i][0]
            yVal = objectPos[i][1]
            
            formattedName = f"{fruit}_{i}"
            
            formattedObject[formattedName] = {"x":xVal,"y":yVal}
            
            # print(f"{fruit}_{i}")
            # print(objectPos[i])
            
    # print("format list below \n\n\n")
            
    # print(formattedObject)
                    
    return formattedObject


# main loop
if __name__ == "__main__":
    import argparse
    #input target.txt, slam.txt
    #output est position of all object in GT map format
    
    parser = argparse.ArgumentParser('Matching the estimated map and the true map')
    parser.add_argument('--slam-est', type=str, default='lab_output/slam.txt') # slam file from the sun


    script_dir = os.path.dirname(os.path.abspath(__file__))     # get current script directory (TargetPoseEst.py)

    # read in camera matrix
    fileK = f'{script_dir}/calibration/param/intrinsic.txt'
    camera_matrix = np.loadtxt(fileK, delimiter=',')

    # init YOLO model
    model_path = f'{script_dir}/YOLO/model/best.pt'
    yolo = Detector(model_path)

    # create a dictionary of all the saved images with their corresponding robot pose
    image_poses = {}
    with open(f'{script_dir}/lab_output/images.txt') as fp:
        for line in fp.readlines():
            pose_dict = ast.literal_eval(line)
            image_poses[pose_dict['imgfname']] = pose_dict['pose']
    #print(image_poses)
    # estimate pose of targets in each image
    target_pose_dict = {}
    detected_type_list = []
    for image_path in image_poses.keys():

        #print(os.path.exists(image_path2))
        input_image = cv2.imread(image_path)
        #print(input_image)
        bounding_boxes, bbox_img = yolo.detect_single_image(input_image)
        # cv2.imshow('bbox', bbox_img)
        # cv2.waitKey(0)
        robot_pose = image_poses[image_path]

        for detection in bounding_boxes:
            # count the occurrence of each target type
            occurrence = detected_type_list.count(detection[0])
            target_pose_dict[f'{detection[0]}_{occurrence}'] = estimate_pose(camera_matrix, detection, robot_pose)
            
            detected_type_list.append(detection[0])

    # merge the estimations of the targets so that there are at most 3 estimations of each target type
    target_est = {}
    target_est = merge_estimations(target_pose_dict)
    
    with open(f'{script_dir}/lab_output/targetsUPSTAR.txt', 'w') as fo:
        json.dump(target_est, fo, indent=4)
        
        
    
    
    for key, coordinates in target_est.items(): 
        coordinates['x'] = max(min(coordinates['x'], 1.43), -1.43) 
        coordinates['y'] = max(min(coordinates['y'], 1.43), -1.43)
        
    
                
            
    # print(target_est)
    # save target pose estimations

    args, _ = parser.parse_known_args()
    
    #TODO UNCOMMENT BELOW
    
    aruco_est = parse_slam_map(args.slam_est)
    
    aruco_est.update(target_est)
    

    #making a "true" map for auto nav

    print('Estimations saved!')
    
    print(aruco_est)
    
    with open(f'{script_dir}/est_maps/estMap1.txt', 'w') as fo:
        json.dump(aruco_est, fo, indent=4)
    
    #TODO ABOVE
        
        
def save_target_to_file(folder_path, base_filename, text):
    # Ensure the folder exists
    os.makedirs(folder_path, exist_ok=True)
    
    # Create the file path
    file_path = os.path.join(folder_path, base_filename + ".txt")
    
    # Check if file already exists, and if so, add an index to the filename
    counter = 1
    while os.path.exists(file_path):
        file_path = os.path.join(folder_path, f"{base_filename}_{counter}.txt")
        counter += 1
    
    # Write the text to the file
    with open(file_path, 'w') as file:
        # file.write(text)
        json.dump(text, file, indent=4)
        
        # with open(f'{script_dir}/lab_output/targetsUPSTAR.txt', 'w') as fo:
        # json.dump(target_est, fo, indent=4)
    
    print(f"File saved as: {file_path}")
    return file_path

def save_slam_to_file(folder_path, base_filename, text):
    # Ensure the folder exists
    os.makedirs(folder_path, exist_ok=True)
    
    # Create the file path
    file_path = os.path.join(folder_path, base_filename + ".txt")
    
    # Check if file already exists, and if so, add an index to the filename
    counter = 1
    while os.path.exists(file_path):
        file_path = os.path.join(folder_path, f"{base_filename}_{counter}.txt")
        counter += 1
    
    # Write the text to the file
    with open(file_path, 'w') as file:
        file.write(text)
        # json.dump(text, file, indent=4)
        
        # with open(f'{script_dir}/lab_output/targetsUPSTAR.txt', 'w') as fo:
        # json.dump(target_est, fo, indent=4)
    
    print(f"File saved as: {file_path}")
    return file_path


with open("lab_output/slam.txt", 'r') as file:
    content = file.read()
    

save_slam_to_file("lab_output/SUBMIT","slam",content)
save_target_to_file("lab_output/SUBMIT","targets",target_est)





import json
import matplotlib.pyplot as plt

# Load data from txt file
with open('est_maps/estMap1.txt', 'r') as file:
    data = json.load(file)

# Create figure and axis
fig, ax = plt.subplots(figsize=(10, 10))

# Add a square boundary (3x3 box at origin)
square = plt.Rectangle((-1.5, -1.5), 3, 3, fill=False, color='red', linewidth=2,label="3x3 Box at Origin")
ax.add_patch(square)

# Plot each obstacle as a circle or a square for ArUco markers
for key, coords in data.items():
    obsName = key.split('_')[0]
    
    if obsName.startswith('aruco'):
        # ArUco markers as squares
        shape = plt.Rectangle((coords['x'] - 0.04, coords['y'] - 0.04), 0.08, 0.08, color='blue', fill=False, linewidth=2)
        ax.text(coords['x'], coords['y'] + 0.05, f'{obsName[5:]}', color='black', ha='center', fontsize=6)
    else:
        # Other obstacles as circles
        shape = plt.Circle((coords['x'], coords['y']), 0.05, color='red', fill=False, linewidth=2)
        ax.text(coords['x'], coords['y'], f'{key}', color='black', ha='center', fontsize=8)
    
    ax.add_patch(shape)

# Set the aspect of the plot to 'equal' to ensure shapes aren't distorted
ax.set_aspect('equal', 'box')

# Set plot limits (adjust as needed)
ax.set_xlim(-1.8, 1.8)
ax.set_ylim(-1.8, 1.8)

# Add labels and a title
plt.title('Path and Obstacles')
plt.xlabel('X Coordinate')
plt.ylabel('Y Coordinate')

# Display the plot
plt.grid(True)
plt.show()